-- british-rowing (1 workouts)
-- Generated by scripts/build-seeds.ts — do not edit manually

insert into public.workouts (id, title, description, workout_type, segments, tags, is_public) values (
  'd0000000-0000-0000-0000-000000000001',
  'Beginner Session 1',
  'British Rowing beginner session: 5x3min work intervals at tempo pace with 1-minute rest.',
  'variable_intervals',
  '[{"duration_type":"time","duration_value":180,"target_intensity":60,"target_watts":null,"target_stroke_rate":20,"target_hr_zone":2},{"duration_type":"time","duration_value":180,"target_intensity":83,"target_watts":null,"target_stroke_rate":24,"target_hr_zone":3},{"duration_type":"time","duration_value":60,"target_intensity":null,"target_watts":null,"target_stroke_rate":null,"target_hr_zone":null,"is_rest":true},{"duration_type":"time","duration_value":180,"target_intensity":83,"target_watts":null,"target_stroke_rate":24,"target_hr_zone":3},{"duration_type":"time","duration_value":60,"target_intensity":null,"target_watts":null,"target_stroke_rate":null,"target_hr_zone":null,"is_rest":true},{"duration_type":"time","duration_value":180,"target_intensity":83,"target_watts":null,"target_stroke_rate":24,"target_hr_zone":3},{"duration_type":"time","duration_value":60,"target_intensity":null,"target_watts":null,"target_stroke_rate":null,"target_hr_zone":null,"is_rest":true},{"duration_type":"time","duration_value":180,"target_intensity":83,"target_watts":null,"target_stroke_rate":24,"target_hr_zone":3},{"duration_type":"time","duration_value":60,"target_intensity":null,"target_watts":null,"target_stroke_rate":null,"target_hr_zone":null,"is_rest":true},{"duration_type":"time","duration_value":180,"target_intensity":83,"target_watts":null,"target_stroke_rate":24,"target_hr_zone":3},{"duration_type":"time","duration_value":180,"target_intensity":60,"target_watts":null,"target_stroke_rate":20,"target_hr_zone":2}]'::jsonb,
  '{beginner,british-rowing,structured}',
  true
);
