-- wolverine (1 workouts)
-- Generated by scripts/build-seeds.ts — do not edit manually

insert into public.workouts (id, title, description, workout_type, segments, tags, is_public) values (
  'c0000000-0000-0000-0000-000000000001',
  'Wolverine WOD 1',
  'Wolverine Plan workout: 4x2000m steady state intervals with 5-minute rest.',
  'variable_intervals',
  '[{"type":"warmup","duration_type":"time","duration_value":300,"target_intensity":60,"target_stroke_rate":20,"target_hr_zone":1},{"type":"work","duration_type":"distance","duration_value":2000,"target_intensity":70,"target_stroke_rate":22,"target_hr_zone":2},{"type":"rest","duration_type":"time","duration_value":300,"target_intensity":null,"target_stroke_rate":null,"target_hr_zone":null},{"type":"work","duration_type":"distance","duration_value":2000,"target_intensity":70,"target_stroke_rate":22,"target_hr_zone":2},{"type":"rest","duration_type":"time","duration_value":300,"target_intensity":null,"target_stroke_rate":null,"target_hr_zone":null},{"type":"work","duration_type":"distance","duration_value":2000,"target_intensity":70,"target_stroke_rate":22,"target_hr_zone":2},{"type":"rest","duration_type":"time","duration_value":300,"target_intensity":null,"target_stroke_rate":null,"target_hr_zone":null},{"type":"work","duration_type":"distance","duration_value":2000,"target_intensity":70,"target_stroke_rate":22,"target_hr_zone":2},{"type":"cooldown","duration_type":"time","duration_value":300,"target_intensity":60,"target_stroke_rate":20,"target_hr_zone":1}]'::jsonb,
  '{wolverine-plan,endurance,long-intervals}',
  true
);
