-- 2k-race-prep (11 workouts)
-- Generated by scripts/build-seeds.ts — do not edit manually

insert into public.workouts (id, title, description, workout_type, segments, tags, is_public) values (
  'f1000000-0000-0000-0001-000000000003',
  '2K Prep Wk1 Easy 5K',
  'Week 1: Easy 5K at low Z2 for recovery and volume.',
  'variable_intervals',
  '[{"duration_type":"time","duration_value":180,"target_intensity":60,"target_stroke_rate":20,"target_hr_zone":2},{"duration_type":"distance","duration_value":5000,"target_intensity":70,"target_stroke_rate":22,"target_hr_zone":2},{"duration_type":"time","duration_value":180,"target_intensity":60,"target_stroke_rate":20,"target_hr_zone":2}]'::jsonb,
  '{2k-race-prep,endurance,week-1}',
  true
);

insert into public.workouts (id, title, description, workout_type, segments, tags, is_public) values (
  'f1000000-0000-0000-0001-000000000002',
  '2K Prep Wk1 Race Pace 4x500m',
  'Week 1: 4x500m at race pace intensity with 3-minute rest.',
  'variable_intervals',
  '[{"duration_type":"time","duration_value":300,"target_intensity":60,"target_stroke_rate":20,"target_hr_zone":2},{"duration_type":"distance","duration_value":500,"target_intensity":112,"target_stroke_rate":30,"target_hr_zone":5},{"duration_type":"time","duration_value":180,"target_intensity":null,"target_stroke_rate":null,"target_hr_zone":null},{"duration_type":"distance","duration_value":500,"target_intensity":112,"target_stroke_rate":30,"target_hr_zone":5},{"duration_type":"time","duration_value":180,"target_intensity":null,"target_stroke_rate":null,"target_hr_zone":null},{"duration_type":"distance","duration_value":500,"target_intensity":112,"target_stroke_rate":30,"target_hr_zone":5},{"duration_type":"time","duration_value":180,"target_intensity":null,"target_stroke_rate":null,"target_hr_zone":null},{"duration_type":"distance","duration_value":500,"target_intensity":112,"target_stroke_rate":30,"target_hr_zone":5},{"duration_type":"time","duration_value":300,"target_intensity":60,"target_stroke_rate":20,"target_hr_zone":2}]'::jsonb,
  '{2k-race-prep,race-pace,intervals,week-1}',
  true
);

insert into public.workouts (id, title, description, workout_type, segments, tags, is_public) values (
  'f1000000-0000-0000-0001-000000000001',
  '2K Prep Wk1 Steady',
  'Week 1: 30-minute steady state at Z2 to build aerobic base.',
  'variable_intervals',
  '[{"duration_type":"time","duration_value":300,"target_intensity":60,"target_stroke_rate":20,"target_hr_zone":2},{"duration_type":"time","duration_value":1800,"target_intensity":70,"target_stroke_rate":22,"target_hr_zone":2},{"duration_type":"time","duration_value":300,"target_intensity":60,"target_stroke_rate":20,"target_hr_zone":2}]'::jsonb,
  '{2k-race-prep,steady-state,week-1}',
  true
);

insert into public.workouts (id, title, description, workout_type, segments, tags, is_public) values (
  'f1000000-0000-0000-0002-000000000003',
  '2K Prep Wk2 Easy 6K',
  'Week 2: Easy 6K at low Z2 for recovery and volume.',
  'variable_intervals',
  '[{"duration_type":"time","duration_value":180,"target_intensity":60,"target_stroke_rate":20,"target_hr_zone":2},{"duration_type":"distance","duration_value":6000,"target_intensity":70,"target_stroke_rate":22,"target_hr_zone":2},{"duration_type":"time","duration_value":180,"target_intensity":60,"target_stroke_rate":20,"target_hr_zone":2}]'::jsonb,
  '{2k-race-prep,endurance,week-2}',
  true
);

insert into public.workouts (id, title, description, workout_type, segments, tags, is_public) values (
  'f1000000-0000-0000-0002-000000000002',
  '2K Prep Wk2 Race Pace 6x500m',
  'Week 2: 6x500m at race pace intensity with 2:30 rest.',
  'variable_intervals',
  '[{"duration_type":"time","duration_value":300,"target_intensity":60,"target_stroke_rate":20,"target_hr_zone":2},{"duration_type":"distance","duration_value":500,"target_intensity":112,"target_stroke_rate":30,"target_hr_zone":5},{"duration_type":"time","duration_value":150,"target_intensity":null,"target_stroke_rate":null,"target_hr_zone":null},{"duration_type":"distance","duration_value":500,"target_intensity":112,"target_stroke_rate":30,"target_hr_zone":5},{"duration_type":"time","duration_value":150,"target_intensity":null,"target_stroke_rate":null,"target_hr_zone":null},{"duration_type":"distance","duration_value":500,"target_intensity":112,"target_stroke_rate":30,"target_hr_zone":5},{"duration_type":"time","duration_value":150,"target_intensity":null,"target_stroke_rate":null,"target_hr_zone":null},{"duration_type":"distance","duration_value":500,"target_intensity":112,"target_stroke_rate":30,"target_hr_zone":5},{"duration_type":"time","duration_value":150,"target_intensity":null,"target_stroke_rate":null,"target_hr_zone":null},{"duration_type":"distance","duration_value":500,"target_intensity":112,"target_stroke_rate":30,"target_hr_zone":5},{"duration_type":"time","duration_value":150,"target_intensity":null,"target_stroke_rate":null,"target_hr_zone":null},{"duration_type":"distance","duration_value":500,"target_intensity":112,"target_stroke_rate":30,"target_hr_zone":5},{"duration_type":"time","duration_value":300,"target_intensity":60,"target_stroke_rate":20,"target_hr_zone":2}]'::jsonb,
  '{2k-race-prep,race-pace,intervals,week-2}',
  true
);

insert into public.workouts (id, title, description, workout_type, segments, tags, is_public) values (
  'f1000000-0000-0000-0002-000000000001',
  '2K Prep Wk2 Tempo 3K',
  'Week 2: 3K at tempo/threshold pace.',
  'variable_intervals',
  '[{"duration_type":"time","duration_value":300,"target_intensity":60,"target_stroke_rate":20,"target_hr_zone":2},{"duration_type":"distance","duration_value":3000,"target_intensity":95,"target_stroke_rate":26,"target_hr_zone":5},{"duration_type":"time","duration_value":300,"target_intensity":60,"target_stroke_rate":20,"target_hr_zone":2}]'::jsonb,
  '{2k-race-prep,tempo,threshold,week-2}',
  true
);

insert into public.workouts (id, title, description, workout_type, segments, tags, is_public) values (
  'f1000000-0000-0000-0003-000000000003',
  '2K Prep Wk3 Easy Recovery',
  'Week 3: 20-minute easy recovery row at Z1.',
  'variable_intervals',
  '[{"duration_type":"time","duration_value":180,"target_intensity":60,"target_stroke_rate":20,"target_hr_zone":2},{"duration_type":"time","duration_value":1200,"target_intensity":55,"target_stroke_rate":20,"target_hr_zone":1},{"duration_type":"time","duration_value":180,"target_intensity":60,"target_stroke_rate":20,"target_hr_zone":2}]'::jsonb,
  '{2k-race-prep,recovery,week-3}',
  true
);

insert into public.workouts (id, title, description, workout_type, segments, tags, is_public) values (
  'f1000000-0000-0000-0003-000000000002',
  '2K Prep Wk3 Race Pace 8x500m',
  'Week 3: 8x500m at race pace intensity with 2-minute rest.',
  'variable_intervals',
  '[{"duration_type":"time","duration_value":300,"target_intensity":60,"target_stroke_rate":20,"target_hr_zone":2},{"duration_type":"distance","duration_value":500,"target_intensity":112,"target_stroke_rate":30,"target_hr_zone":5},{"duration_type":"time","duration_value":120,"target_intensity":null,"target_stroke_rate":null,"target_hr_zone":null},{"duration_type":"distance","duration_value":500,"target_intensity":112,"target_stroke_rate":30,"target_hr_zone":5},{"duration_type":"time","duration_value":120,"target_intensity":null,"target_stroke_rate":null,"target_hr_zone":null},{"duration_type":"distance","duration_value":500,"target_intensity":112,"target_stroke_rate":30,"target_hr_zone":5},{"duration_type":"time","duration_value":120,"target_intensity":null,"target_stroke_rate":null,"target_hr_zone":null},{"duration_type":"distance","duration_value":500,"target_intensity":112,"target_stroke_rate":30,"target_hr_zone":5},{"duration_type":"time","duration_value":120,"target_intensity":null,"target_stroke_rate":null,"target_hr_zone":null},{"duration_type":"distance","duration_value":500,"target_intensity":112,"target_stroke_rate":30,"target_hr_zone":5},{"duration_type":"time","duration_value":120,"target_intensity":null,"target_stroke_rate":null,"target_hr_zone":null},{"duration_type":"distance","duration_value":500,"target_intensity":112,"target_stroke_rate":30,"target_hr_zone":5},{"duration_type":"time","duration_value":120,"target_intensity":null,"target_stroke_rate":null,"target_hr_zone":null},{"duration_type":"distance","duration_value":500,"target_intensity":112,"target_stroke_rate":30,"target_hr_zone":5},{"duration_type":"time","duration_value":120,"target_intensity":null,"target_stroke_rate":null,"target_hr_zone":null},{"duration_type":"distance","duration_value":500,"target_intensity":112,"target_stroke_rate":30,"target_hr_zone":5},{"duration_type":"time","duration_value":300,"target_intensity":60,"target_stroke_rate":20,"target_hr_zone":2}]'::jsonb,
  '{2k-race-prep,race-pace,intervals,week-3}',
  true
);

insert into public.workouts (id, title, description, workout_type, segments, tags, is_public) values (
  'f1000000-0000-0000-0003-000000000001',
  '2K Prep Wk3 Threshold 2x1500m',
  'Week 3: 2x1500m at threshold intensity with 5-minute rest.',
  'variable_intervals',
  '[{"duration_type":"time","duration_value":300,"target_intensity":60,"target_stroke_rate":20,"target_hr_zone":2},{"duration_type":"distance","duration_value":1500,"target_intensity":95,"target_stroke_rate":26,"target_hr_zone":5},{"duration_type":"time","duration_value":300,"target_intensity":null,"target_stroke_rate":null,"target_hr_zone":null},{"duration_type":"distance","duration_value":1500,"target_intensity":95,"target_stroke_rate":26,"target_hr_zone":5},{"duration_type":"time","duration_value":300,"target_intensity":60,"target_stroke_rate":20,"target_hr_zone":2}]'::jsonb,
  '{2k-race-prep,threshold,week-3}',
  true
);

insert into public.workouts (id, title, description, workout_type, segments, tags, is_public) values (
  'f1000000-0000-0000-0004-000000000002',
  '2K Prep Wk4 Openers',
  'Week 4: 4x250m openers at race pace+ with full 4-minute recovery.',
  'variable_intervals',
  '[{"duration_type":"time","duration_value":180,"target_intensity":60,"target_stroke_rate":20,"target_hr_zone":2},{"duration_type":"distance","duration_value":250,"target_intensity":112,"target_stroke_rate":30,"target_hr_zone":5},{"duration_type":"time","duration_value":240,"target_intensity":null,"target_stroke_rate":null,"target_hr_zone":null},{"duration_type":"distance","duration_value":250,"target_intensity":112,"target_stroke_rate":30,"target_hr_zone":5},{"duration_type":"time","duration_value":240,"target_intensity":null,"target_stroke_rate":null,"target_hr_zone":null},{"duration_type":"distance","duration_value":250,"target_intensity":112,"target_stroke_rate":30,"target_hr_zone":5},{"duration_type":"time","duration_value":240,"target_intensity":null,"target_stroke_rate":null,"target_hr_zone":null},{"duration_type":"distance","duration_value":250,"target_intensity":112,"target_stroke_rate":30,"target_hr_zone":5},{"duration_type":"time","duration_value":180,"target_intensity":60,"target_stroke_rate":20,"target_hr_zone":2}]'::jsonb,
  '{2k-race-prep,race-pace,openers,week-4}',
  true
);

insert into public.workouts (id, title, description, workout_type, segments, tags, is_public) values (
  'f1000000-0000-0000-0004-000000000001',
  '2K Prep Wk4 Shakeout',
  'Week 4: Light shakeout with 3 short pickups to stay sharp before race day.',
  'variable_intervals',
  '[{"duration_type":"time","duration_value":300,"target_intensity":60,"target_stroke_rate":20,"target_hr_zone":2},{"duration_type":"time","duration_value":30,"target_intensity":112,"target_stroke_rate":30,"target_hr_zone":5},{"duration_type":"time","duration_value":90,"target_intensity":null,"target_stroke_rate":null,"target_hr_zone":null},{"duration_type":"time","duration_value":30,"target_intensity":112,"target_stroke_rate":30,"target_hr_zone":5},{"duration_type":"time","duration_value":90,"target_intensity":null,"target_stroke_rate":null,"target_hr_zone":null},{"duration_type":"time","duration_value":30,"target_intensity":112,"target_stroke_rate":30,"target_hr_zone":5},{"duration_type":"time","duration_value":300,"target_intensity":60,"target_stroke_rate":20,"target_hr_zone":2}]'::jsonb,
  '{2k-race-prep,shakeout,week-4}',
  true
);
