-- zone1-recovery (10 workouts)
-- Generated by scripts/build-seeds.ts — do not edit manually

insert into public.workouts (id, title, description, workout_type, segments, tags, is_public) values (
  '10000000-0000-0000-0000-000000000007',
  'Active Recovery 30',
  '30 minutes with gentle rate progression. Easy aerobic flush.',
  'variable_intervals',
  '[{"duration_type":"time","duration_value":180,"target_intensity":50,"target_watts":null,"target_stroke_rate":20,"target_hr_zone":null},{"duration_type":"time","duration_value":360,"target_intensity":55,"target_watts":null,"target_stroke_rate":16,"target_hr_zone":1},{"duration_type":"time","duration_value":360,"target_intensity":55,"target_watts":null,"target_stroke_rate":18,"target_hr_zone":1},{"duration_type":"time","duration_value":360,"target_intensity":55,"target_watts":null,"target_stroke_rate":20,"target_hr_zone":1},{"duration_type":"time","duration_value":360,"target_intensity":55,"target_watts":null,"target_stroke_rate":18,"target_hr_zone":1},{"duration_type":"time","duration_value":180,"target_intensity":50,"target_watts":null,"target_stroke_rate":20,"target_hr_zone":null}]'::jsonb,
  '{recovery,30-min}',
  true
);

insert into public.workouts (id, title, description, workout_type, segments, tags, is_public) values (
  '10000000-0000-0000-0000-000000000008',
  'Easy Distance 4K',
  '4K at easy pace. Short and light.',
  'variable_intervals',
  '[{"duration_type":"distance","duration_value":500,"target_intensity":50,"target_watts":null,"target_stroke_rate":20,"target_hr_zone":null},{"duration_type":"distance","duration_value":3000,"target_intensity":55,"target_watts":null,"target_stroke_rate":20,"target_hr_zone":1},{"duration_type":"distance","duration_value":500,"target_intensity":50,"target_watts":null,"target_stroke_rate":20,"target_hr_zone":null}]'::jsonb,
  '{recovery,distance}',
  true
);

insert into public.workouts (id, title, description, workout_type, segments, tags, is_public) values (
  '10000000-0000-0000-0000-000000000001',
  'Easy Spin',
  '20 minutes of easy spinning. No pressure, just move.',
  'variable_intervals',
  '[{"duration_type":"time","duration_value":180,"target_intensity":50,"target_watts":null,"target_stroke_rate":20,"target_hr_zone":null},{"duration_type":"time","duration_value":1200,"target_intensity":55,"target_watts":null,"target_stroke_rate":20,"target_hr_zone":1},{"duration_type":"time","duration_value":180,"target_intensity":50,"target_watts":null,"target_stroke_rate":20,"target_hr_zone":null}]'::jsonb,
  '{recovery,easy,beginner-friendly}',
  true
);

insert into public.workouts (id, title, description, workout_type, segments, tags, is_public) values (
  '10000000-0000-0000-0000-00000000000a',
  'Flush Row',
  'Quick 20-minute flush. Perfect for active rest days.',
  'variable_intervals',
  '[{"duration_type":"time","duration_value":300,"target_intensity":50,"target_watts":null,"target_stroke_rate":20,"target_hr_zone":null},{"duration_type":"time","duration_value":600,"target_intensity":55,"target_watts":null,"target_stroke_rate":20,"target_hr_zone":1},{"duration_type":"time","duration_value":300,"target_intensity":50,"target_watts":null,"target_stroke_rate":20,"target_hr_zone":null}]'::jsonb,
  '{recovery,short,flush}',
  true
);

insert into public.workouts (id, title, description, workout_type, segments, tags, is_public) values (
  '10000000-0000-0000-0000-000000000004',
  'Light Intervals',
  'Gentle intervals with rest. Keep it conversational.',
  'variable_intervals',
  '[{"duration_type":"time","duration_value":180,"target_intensity":50,"target_watts":null,"target_stroke_rate":20,"target_hr_zone":null},{"duration_type":"time","duration_value":180,"target_intensity":55,"target_watts":null,"target_stroke_rate":20,"target_hr_zone":1},{"duration_type":"time","duration_value":60,"target_intensity":null,"target_watts":null,"target_stroke_rate":null,"target_hr_zone":null,"is_rest":true},{"duration_type":"time","duration_value":180,"target_intensity":55,"target_watts":null,"target_stroke_rate":20,"target_hr_zone":1},{"duration_type":"time","duration_value":60,"target_intensity":null,"target_watts":null,"target_stroke_rate":null,"target_hr_zone":null,"is_rest":true},{"duration_type":"time","duration_value":180,"target_intensity":55,"target_watts":null,"target_stroke_rate":20,"target_hr_zone":1},{"duration_type":"time","duration_value":60,"target_intensity":null,"target_watts":null,"target_stroke_rate":null,"target_hr_zone":null,"is_rest":true},{"duration_type":"time","duration_value":180,"target_intensity":55,"target_watts":null,"target_stroke_rate":20,"target_hr_zone":1},{"duration_type":"time","duration_value":180,"target_intensity":50,"target_watts":null,"target_stroke_rate":20,"target_hr_zone":null}]'::jsonb,
  '{recovery,intervals}',
  true
);

insert into public.workouts (id, title, description, workout_type, segments, tags, is_public) values (
  '10000000-0000-0000-0000-000000000009',
  'Pause and Breathe',
  '5-minute blocks with generous rest. Practice breathing rhythm.',
  'variable_intervals',
  '[{"duration_type":"time","duration_value":180,"target_intensity":50,"target_watts":null,"target_stroke_rate":20,"target_hr_zone":null},{"duration_type":"time","duration_value":300,"target_intensity":55,"target_watts":null,"target_stroke_rate":20,"target_hr_zone":1},{"duration_type":"time","duration_value":120,"target_intensity":null,"target_watts":null,"target_stroke_rate":null,"target_hr_zone":null,"is_rest":true},{"duration_type":"time","duration_value":300,"target_intensity":55,"target_watts":null,"target_stroke_rate":20,"target_hr_zone":1},{"duration_type":"time","duration_value":120,"target_intensity":null,"target_watts":null,"target_stroke_rate":null,"target_hr_zone":null,"is_rest":true},{"duration_type":"time","duration_value":300,"target_intensity":55,"target_watts":null,"target_stroke_rate":20,"target_hr_zone":1},{"duration_type":"time","duration_value":180,"target_intensity":50,"target_watts":null,"target_stroke_rate":20,"target_hr_zone":null}]'::jsonb,
  '{recovery,breathing}',
  true
);

insert into public.workouts (id, title, description, workout_type, segments, tags, is_public) values (
  '10000000-0000-0000-0000-000000000006',
  'Post-Race Recovery',
  'Very light session after a hard effort. Move blood, don''t make power.',
  'variable_intervals',
  '[{"duration_type":"time","duration_value":300,"target_intensity":50,"target_watts":null,"target_stroke_rate":20,"target_hr_zone":null},{"duration_type":"time","duration_value":900,"target_intensity":55,"target_watts":null,"target_stroke_rate":20,"target_hr_zone":1},{"duration_type":"time","duration_value":300,"target_intensity":50,"target_watts":null,"target_stroke_rate":20,"target_hr_zone":null}]'::jsonb,
  '{recovery,post-race}',
  true
);

insert into public.workouts (id, title, description, workout_type, segments, tags, is_public) values (
  '10000000-0000-0000-0000-000000000002',
  'Recovery Paddle',
  '25 minutes at recovery pace. Gentle strokes, easy breathing.',
  'variable_intervals',
  '[{"duration_type":"time","duration_value":180,"target_intensity":50,"target_watts":null,"target_stroke_rate":20,"target_hr_zone":null},{"duration_type":"time","duration_value":1500,"target_intensity":55,"target_watts":null,"target_stroke_rate":20,"target_hr_zone":1},{"duration_type":"time","duration_value":180,"target_intensity":50,"target_watts":null,"target_stroke_rate":20,"target_hr_zone":null}]'::jsonb,
  '{recovery,easy}',
  true
);

insert into public.workouts (id, title, description, workout_type, segments, tags, is_public) values (
  '10000000-0000-0000-0000-000000000003',
  'Stroke Rate Ladder (Easy)',
  'Rate changes at easy pace. Focus on stroke mechanics at each rate.',
  'variable_intervals',
  '[{"duration_type":"time","duration_value":180,"target_intensity":50,"target_watts":null,"target_stroke_rate":20,"target_hr_zone":null},{"duration_type":"time","duration_value":300,"target_intensity":55,"target_watts":null,"target_stroke_rate":16,"target_hr_zone":1},{"duration_type":"time","duration_value":300,"target_intensity":55,"target_watts":null,"target_stroke_rate":18,"target_hr_zone":1},{"duration_type":"time","duration_value":300,"target_intensity":55,"target_watts":null,"target_stroke_rate":20,"target_hr_zone":1},{"duration_type":"time","duration_value":300,"target_intensity":55,"target_watts":null,"target_stroke_rate":18,"target_hr_zone":1},{"duration_type":"time","duration_value":300,"target_intensity":55,"target_watts":null,"target_stroke_rate":16,"target_hr_zone":1},{"duration_type":"time","duration_value":180,"target_intensity":50,"target_watts":null,"target_stroke_rate":20,"target_hr_zone":null}]'::jsonb,
  '{recovery,technique,rate-ladder}',
  true
);

insert into public.workouts (id, title, description, workout_type, segments, tags, is_public) values (
  '10000000-0000-0000-0000-000000000005',
  'Technique Focus',
  'Alternate low and moderate rates at easy pace. Focus on body position.',
  'variable_intervals',
  '[{"duration_type":"time","duration_value":180,"target_intensity":50,"target_watts":null,"target_stroke_rate":20,"target_hr_zone":null},{"duration_type":"time","duration_value":120,"target_intensity":55,"target_watts":null,"target_stroke_rate":20,"target_hr_zone":1},{"duration_type":"time","duration_value":60,"target_intensity":55,"target_watts":null,"target_stroke_rate":20,"target_hr_zone":1},{"duration_type":"time","duration_value":120,"target_intensity":55,"target_watts":null,"target_stroke_rate":20,"target_hr_zone":1},{"duration_type":"time","duration_value":60,"target_intensity":55,"target_watts":null,"target_stroke_rate":20,"target_hr_zone":1},{"duration_type":"time","duration_value":120,"target_intensity":55,"target_watts":null,"target_stroke_rate":20,"target_hr_zone":1},{"duration_type":"time","duration_value":60,"target_intensity":55,"target_watts":null,"target_stroke_rate":20,"target_hr_zone":1},{"duration_type":"time","duration_value":120,"target_intensity":55,"target_watts":null,"target_stroke_rate":20,"target_hr_zone":1},{"duration_type":"time","duration_value":60,"target_intensity":55,"target_watts":null,"target_stroke_rate":20,"target_hr_zone":1},{"duration_type":"time","duration_value":120,"target_intensity":55,"target_watts":null,"target_stroke_rate":20,"target_hr_zone":1},{"duration_type":"time","duration_value":60,"target_intensity":55,"target_watts":null,"target_stroke_rate":20,"target_hr_zone":1},{"duration_type":"time","duration_value":120,"target_intensity":55,"target_watts":null,"target_stroke_rate":20,"target_hr_zone":1},{"duration_type":"time","duration_value":60,"target_intensity":55,"target_watts":null,"target_stroke_rate":20,"target_hr_zone":1},{"duration_type":"time","duration_value":180,"target_intensity":50,"target_watts":null,"target_stroke_rate":20,"target_hr_zone":null}]'::jsonb,
  '{recovery,technique}',
  true
);
