-- zone3-tempo (10 workouts)
-- Generated by scripts/build-seeds.ts — do not edit manually

insert into public.workouts (id, title, description, workout_type, segments, tags, is_public) values (
  '30000000-0000-0000-0000-000000000001',
  'Classic Tempo 5x5',
  'Five 5-minute tempo efforts. The classic tempo session.',
  'variable_intervals',
  '[{"duration_type":"time","duration_value":300,"target_intensity":60,"target_stroke_rate":20,"target_hr_zone":2},{"duration_type":"time","duration_value":300,"target_intensity":83,"target_stroke_rate":24,"target_hr_zone":3},{"duration_type":"time","duration_value":120,"target_intensity":null,"target_stroke_rate":null,"target_hr_zone":null,"is_rest":true},{"duration_type":"time","duration_value":300,"target_intensity":83,"target_stroke_rate":24,"target_hr_zone":3},{"duration_type":"time","duration_value":120,"target_intensity":null,"target_stroke_rate":null,"target_hr_zone":null,"is_rest":true},{"duration_type":"time","duration_value":300,"target_intensity":83,"target_stroke_rate":24,"target_hr_zone":3},{"duration_type":"time","duration_value":120,"target_intensity":null,"target_stroke_rate":null,"target_hr_zone":null,"is_rest":true},{"duration_type":"time","duration_value":300,"target_intensity":83,"target_stroke_rate":24,"target_hr_zone":3},{"duration_type":"time","duration_value":120,"target_intensity":null,"target_stroke_rate":null,"target_hr_zone":null,"is_rest":true},{"duration_type":"time","duration_value":300,"target_intensity":83,"target_stroke_rate":24,"target_hr_zone":3},{"duration_type":"time","duration_value":300,"target_intensity":60,"target_stroke_rate":20,"target_hr_zone":2}]'::jsonb,
  '{tempo,intervals,classic}',
  true
);

insert into public.workouts (id, title, description, workout_type, segments, tags, is_public) values (
  '30000000-0000-0000-0000-000000000007',
  'Countdown (8/6/4/2)',
  'Descending intervals, ascending effort. Shorter gets harder.',
  'variable_intervals',
  '[{"duration_type":"time","duration_value":300,"target_intensity":60,"target_stroke_rate":20,"target_hr_zone":2},{"duration_type":"time","duration_value":480,"target_intensity":83,"target_stroke_rate":24,"target_hr_zone":3},{"duration_type":"time","duration_value":180,"target_intensity":null,"target_stroke_rate":null,"target_hr_zone":null},{"duration_type":"time","duration_value":360,"target_intensity":83,"target_stroke_rate":24,"target_hr_zone":3},{"duration_type":"time","duration_value":180,"target_intensity":null,"target_stroke_rate":null,"target_hr_zone":null},{"duration_type":"time","duration_value":240,"target_intensity":83,"target_stroke_rate":24,"target_hr_zone":3},{"duration_type":"time","duration_value":180,"target_intensity":null,"target_stroke_rate":null,"target_hr_zone":null},{"duration_type":"time","duration_value":120,"target_intensity":83,"target_stroke_rate":24,"target_hr_zone":3},{"duration_type":"time","duration_value":180,"target_intensity":null,"target_stroke_rate":null,"target_hr_zone":null},{"duration_type":"time","duration_value":300,"target_intensity":60,"target_stroke_rate":20,"target_hr_zone":2}]'::jsonb,
  '{tempo,descending,countdown}',
  true
);

insert into public.workouts (id, title, description, workout_type, segments, tags, is_public) values (
  '30000000-0000-0000-0000-000000000003',
  'Fartlek Tempo',
  'Alternate tempo and easy every 2 minutes. Fartlek-style.',
  'variable_intervals',
  '[{"duration_type":"time","duration_value":300,"target_intensity":60,"target_stroke_rate":20,"target_hr_zone":2},{"duration_type":"time","duration_value":120,"target_intensity":83,"target_stroke_rate":24,"target_hr_zone":3},{"duration_type":"time","duration_value":120,"target_intensity":70,"target_stroke_rate":22,"target_hr_zone":2},{"duration_type":"time","duration_value":120,"target_intensity":83,"target_stroke_rate":24,"target_hr_zone":3},{"duration_type":"time","duration_value":120,"target_intensity":70,"target_stroke_rate":22,"target_hr_zone":2},{"duration_type":"time","duration_value":120,"target_intensity":83,"target_stroke_rate":24,"target_hr_zone":3},{"duration_type":"time","duration_value":120,"target_intensity":70,"target_stroke_rate":22,"target_hr_zone":2},{"duration_type":"time","duration_value":120,"target_intensity":83,"target_stroke_rate":24,"target_hr_zone":3},{"duration_type":"time","duration_value":120,"target_intensity":70,"target_stroke_rate":22,"target_hr_zone":2},{"duration_type":"time","duration_value":120,"target_intensity":83,"target_stroke_rate":24,"target_hr_zone":3},{"duration_type":"time","duration_value":120,"target_intensity":70,"target_stroke_rate":22,"target_hr_zone":2},{"duration_type":"time","duration_value":120,"target_intensity":83,"target_stroke_rate":24,"target_hr_zone":3},{"duration_type":"time","duration_value":120,"target_intensity":70,"target_stroke_rate":22,"target_hr_zone":2},{"duration_type":"time","duration_value":120,"target_intensity":83,"target_stroke_rate":24,"target_hr_zone":3},{"duration_type":"time","duration_value":120,"target_intensity":70,"target_stroke_rate":22,"target_hr_zone":2},{"duration_type":"time","duration_value":300,"target_intensity":60,"target_stroke_rate":20,"target_hr_zone":2}]'::jsonb,
  '{tempo,fartlek}',
  true
);

insert into public.workouts (id, title, description, workout_type, segments, tags, is_public) values (
  '30000000-0000-0000-0000-00000000000a',
  'Long Tempo Build',
  'Build from aerobic to tempo then ease off. Progressive session.',
  'variable_intervals',
  '[{"duration_type":"time","duration_value":300,"target_intensity":60,"target_stroke_rate":20,"target_hr_zone":2},{"duration_type":"time","duration_value":600,"target_intensity":70,"target_stroke_rate":22,"target_hr_zone":2},{"duration_type":"time","duration_value":900,"target_intensity":83,"target_stroke_rate":24,"target_hr_zone":3},{"duration_type":"time","duration_value":300,"target_intensity":70,"target_stroke_rate":22,"target_hr_zone":2},{"duration_type":"time","duration_value":300,"target_intensity":60,"target_stroke_rate":20,"target_hr_zone":2}]'::jsonb,
  '{tempo,build,progression}',
  true
);

insert into public.workouts (id, title, description, workout_type, segments, tags, is_public) values (
  '30000000-0000-0000-0000-000000000005',
  'Rate Ladder Tempo',
  'Ascending rate at tempo pace. Same effort, different feel.',
  'variable_intervals',
  '[{"duration_type":"time","duration_value":300,"target_intensity":60,"target_stroke_rate":20,"target_hr_zone":2},{"duration_type":"time","duration_value":300,"target_intensity":83,"target_stroke_rate":22,"target_hr_zone":3},{"duration_type":"time","duration_value":60,"target_intensity":null,"target_stroke_rate":null,"target_hr_zone":null},{"duration_type":"time","duration_value":300,"target_intensity":83,"target_stroke_rate":24,"target_hr_zone":3},{"duration_type":"time","duration_value":60,"target_intensity":null,"target_stroke_rate":null,"target_hr_zone":null},{"duration_type":"time","duration_value":300,"target_intensity":83,"target_stroke_rate":26,"target_hr_zone":3},{"duration_type":"time","duration_value":60,"target_intensity":null,"target_stroke_rate":null,"target_hr_zone":null},{"duration_type":"time","duration_value":300,"target_intensity":83,"target_stroke_rate":28,"target_hr_zone":3},{"duration_type":"time","duration_value":60,"target_intensity":null,"target_stroke_rate":null,"target_hr_zone":null},{"duration_type":"time","duration_value":300,"target_intensity":83,"target_stroke_rate":26,"target_hr_zone":3},{"duration_type":"time","duration_value":60,"target_intensity":null,"target_stroke_rate":null,"target_hr_zone":null},{"duration_type":"time","duration_value":300,"target_intensity":60,"target_stroke_rate":20,"target_hr_zone":2}]'::jsonb,
  '{tempo,rate-ladder}',
  true
);

insert into public.workouts (id, title, description, workout_type, segments, tags, is_public) values (
  '30000000-0000-0000-0000-000000000009',
  'Swing Tempo',
  'Swing between tempo and easy. Feel the contrast.',
  'variable_intervals',
  '[{"duration_type":"time","duration_value":300,"target_intensity":60,"target_stroke_rate":20,"target_hr_zone":2},{"duration_type":"time","duration_value":180,"target_intensity":83,"target_stroke_rate":24,"target_hr_zone":3},{"duration_type":"time","duration_value":180,"target_intensity":70,"target_stroke_rate":22,"target_hr_zone":2},{"duration_type":"time","duration_value":180,"target_intensity":83,"target_stroke_rate":24,"target_hr_zone":3},{"duration_type":"time","duration_value":180,"target_intensity":70,"target_stroke_rate":22,"target_hr_zone":2},{"duration_type":"time","duration_value":180,"target_intensity":83,"target_stroke_rate":24,"target_hr_zone":3},{"duration_type":"time","duration_value":180,"target_intensity":70,"target_stroke_rate":22,"target_hr_zone":2},{"duration_type":"time","duration_value":180,"target_intensity":83,"target_stroke_rate":24,"target_hr_zone":3},{"duration_type":"time","duration_value":180,"target_intensity":70,"target_stroke_rate":22,"target_hr_zone":2},{"duration_type":"time","duration_value":300,"target_intensity":60,"target_stroke_rate":20,"target_hr_zone":2}]'::jsonb,
  '{tempo,swing}',
  true
);

insert into public.workouts (id, title, description, workout_type, segments, tags, is_public) values (
  '30000000-0000-0000-0000-000000000008',
  'Tempo 1K Repeats',
  'Six 1K repeats at tempo pace.',
  'variable_intervals',
  '[{"duration_type":"time","duration_value":300,"target_intensity":60,"target_stroke_rate":20,"target_hr_zone":2},{"duration_type":"distance","duration_value":1000,"target_intensity":83,"target_stroke_rate":24,"target_hr_zone":3},{"duration_type":"time","duration_value":90,"target_intensity":null,"target_stroke_rate":null,"target_hr_zone":null,"is_rest":true},{"duration_type":"distance","duration_value":1000,"target_intensity":83,"target_stroke_rate":24,"target_hr_zone":3},{"duration_type":"time","duration_value":90,"target_intensity":null,"target_stroke_rate":null,"target_hr_zone":null,"is_rest":true},{"duration_type":"distance","duration_value":1000,"target_intensity":83,"target_stroke_rate":24,"target_hr_zone":3},{"duration_type":"time","duration_value":90,"target_intensity":null,"target_stroke_rate":null,"target_hr_zone":null,"is_rest":true},{"duration_type":"distance","duration_value":1000,"target_intensity":83,"target_stroke_rate":24,"target_hr_zone":3},{"duration_type":"time","duration_value":90,"target_intensity":null,"target_stroke_rate":null,"target_hr_zone":null,"is_rest":true},{"duration_type":"distance","duration_value":1000,"target_intensity":83,"target_stroke_rate":24,"target_hr_zone":3},{"duration_type":"time","duration_value":90,"target_intensity":null,"target_stroke_rate":null,"target_hr_zone":null,"is_rest":true},{"duration_type":"distance","duration_value":1000,"target_intensity":83,"target_stroke_rate":24,"target_hr_zone":3},{"duration_type":"time","duration_value":300,"target_intensity":60,"target_stroke_rate":20,"target_hr_zone":2}]'::jsonb,
  '{tempo,intervals,distance}',
  true
);

insert into public.workouts (id, title, description, workout_type, segments, tags, is_public) values (
  '30000000-0000-0000-0000-000000000006',
  'Tempo 20',
  '20 minutes sustained tempo. No intervals, just hold the effort.',
  'variable_intervals',
  '[{"duration_type":"time","duration_value":300,"target_intensity":60,"target_stroke_rate":20,"target_hr_zone":2},{"duration_type":"time","duration_value":1200,"target_intensity":83,"target_stroke_rate":24,"target_hr_zone":3},{"duration_type":"time","duration_value":300,"target_intensity":60,"target_stroke_rate":20,"target_hr_zone":2}]'::jsonb,
  '{tempo,sustained}',
  true
);

insert into public.workouts (id, title, description, workout_type, segments, tags, is_public) values (
  '30000000-0000-0000-0000-000000000002',
  'Tempo 3x10',
  'Three 10-minute tempo blocks. Build sustained tempo fitness.',
  'variable_intervals',
  '[{"duration_type":"time","duration_value":300,"target_intensity":60,"target_stroke_rate":20,"target_hr_zone":2},{"duration_type":"time","duration_value":600,"target_intensity":83,"target_stroke_rate":24,"target_hr_zone":3},{"duration_type":"time","duration_value":180,"target_intensity":null,"target_stroke_rate":null,"target_hr_zone":null,"is_rest":true},{"duration_type":"time","duration_value":600,"target_intensity":83,"target_stroke_rate":24,"target_hr_zone":3},{"duration_type":"time","duration_value":180,"target_intensity":null,"target_stroke_rate":null,"target_hr_zone":null,"is_rest":true},{"duration_type":"time","duration_value":600,"target_intensity":83,"target_stroke_rate":24,"target_hr_zone":3},{"duration_type":"time","duration_value":300,"target_intensity":60,"target_stroke_rate":20,"target_hr_zone":2}]'::jsonb,
  '{tempo,intervals,long}',
  true
);

insert into public.workouts (id, title, description, workout_type, segments, tags, is_public) values (
  '30000000-0000-0000-0000-000000000004',
  'Tempo Distance Pyramid',
  'Distance pyramid at tempo. Peak at 1500m then come back down.',
  'variable_intervals',
  '[{"duration_type":"time","duration_value":300,"target_intensity":60,"target_stroke_rate":20,"target_hr_zone":2},{"duration_type":"distance","duration_value":500,"target_intensity":83,"target_stroke_rate":24,"target_hr_zone":3},{"duration_type":"time","duration_value":120,"target_intensity":null,"target_stroke_rate":null,"target_hr_zone":null},{"duration_type":"distance","duration_value":1000,"target_intensity":83,"target_stroke_rate":24,"target_hr_zone":3},{"duration_type":"time","duration_value":120,"target_intensity":null,"target_stroke_rate":null,"target_hr_zone":null},{"duration_type":"distance","duration_value":1500,"target_intensity":83,"target_stroke_rate":24,"target_hr_zone":3},{"duration_type":"time","duration_value":120,"target_intensity":null,"target_stroke_rate":null,"target_hr_zone":null},{"duration_type":"distance","duration_value":1000,"target_intensity":83,"target_stroke_rate":24,"target_hr_zone":3},{"duration_type":"time","duration_value":120,"target_intensity":null,"target_stroke_rate":null,"target_hr_zone":null},{"duration_type":"distance","duration_value":500,"target_intensity":83,"target_stroke_rate":24,"target_hr_zone":3},{"duration_type":"time","duration_value":120,"target_intensity":null,"target_stroke_rate":null,"target_hr_zone":null},{"duration_type":"time","duration_value":300,"target_intensity":60,"target_stroke_rate":20,"target_hr_zone":2}]'::jsonb,
  '{tempo,pyramid,distance}',
  true
);
