-- zone2-aerobic (10 workouts)
-- Generated by scripts/build-seeds.ts — do not edit manually

insert into public.workouts (id, title, description, workout_type, segments, tags, is_public) values (
  '20000000-0000-0000-0000-000000000007',
  'Aerobic Cruise 8K',
  '8K distance piece at aerobic pace.',
  'variable_intervals',
  '[{"duration_type":"distance","duration_value":1000,"target_intensity":60,"target_watts":null,"target_stroke_rate":20,"target_hr_zone":1},{"duration_type":"distance","duration_value":6000,"target_intensity":70,"target_watts":null,"target_stroke_rate":22,"target_hr_zone":1},{"duration_type":"distance","duration_value":1000,"target_intensity":60,"target_watts":null,"target_stroke_rate":20,"target_hr_zone":1}]'::jsonb,
  '{aerobic,distance}',
  true
);

insert into public.workouts (id, title, description, workout_type, segments, tags, is_public) values (
  '20000000-0000-0000-0000-000000000005',
  'Distance Pyramid',
  'Ascending and descending distance at steady pace.',
  'variable_intervals',
  '[{"duration_type":"time","duration_value":300,"target_intensity":60,"target_watts":null,"target_stroke_rate":20,"target_hr_zone":1},{"duration_type":"distance","duration_value":1000,"target_intensity":70,"target_watts":null,"target_stroke_rate":22,"target_hr_zone":1},{"duration_type":"time","duration_value":120,"target_intensity":null,"target_watts":null,"target_stroke_rate":null,"target_hr_zone":null},{"duration_type":"distance","duration_value":2000,"target_intensity":70,"target_watts":null,"target_stroke_rate":22,"target_hr_zone":1},{"duration_type":"time","duration_value":120,"target_intensity":null,"target_watts":null,"target_stroke_rate":null,"target_hr_zone":null},{"duration_type":"distance","duration_value":3000,"target_intensity":70,"target_watts":null,"target_stroke_rate":22,"target_hr_zone":1},{"duration_type":"time","duration_value":120,"target_intensity":null,"target_watts":null,"target_stroke_rate":null,"target_hr_zone":null},{"duration_type":"distance","duration_value":2000,"target_intensity":70,"target_watts":null,"target_stroke_rate":22,"target_hr_zone":1},{"duration_type":"time","duration_value":120,"target_intensity":null,"target_watts":null,"target_stroke_rate":null,"target_hr_zone":null},{"duration_type":"distance","duration_value":1000,"target_intensity":70,"target_watts":null,"target_stroke_rate":22,"target_hr_zone":1},{"duration_type":"time","duration_value":120,"target_intensity":null,"target_watts":null,"target_stroke_rate":null,"target_hr_zone":null},{"duration_type":"time","duration_value":300,"target_intensity":60,"target_watts":null,"target_stroke_rate":20,"target_hr_zone":1}]'::jsonb,
  '{aerobic,pyramid,distance}',
  true
);

insert into public.workouts (id, title, description, workout_type, segments, tags, is_public) values (
  '20000000-0000-0000-0000-000000000008',
  'Easy Tempo Mix',
  'Aerobic blocks with easy recovery dips.',
  'variable_intervals',
  '[{"duration_type":"time","duration_value":300,"target_intensity":60,"target_watts":null,"target_stroke_rate":20,"target_hr_zone":1},{"duration_type":"time","duration_value":480,"target_intensity":70,"target_watts":null,"target_stroke_rate":22,"target_hr_zone":1},{"duration_type":"time","duration_value":120,"target_intensity":55,"target_watts":null,"target_stroke_rate":20,"target_hr_zone":1},{"duration_type":"time","duration_value":480,"target_intensity":70,"target_watts":null,"target_stroke_rate":22,"target_hr_zone":1},{"duration_type":"time","duration_value":120,"target_intensity":55,"target_watts":null,"target_stroke_rate":20,"target_hr_zone":1},{"duration_type":"time","duration_value":480,"target_intensity":70,"target_watts":null,"target_stroke_rate":22,"target_hr_zone":1},{"duration_type":"time","duration_value":120,"target_intensity":55,"target_watts":null,"target_stroke_rate":20,"target_hr_zone":1},{"duration_type":"time","duration_value":300,"target_intensity":60,"target_watts":null,"target_stroke_rate":20,"target_hr_zone":1}]'::jsonb,
  '{aerobic,mixed}',
  true
);

insert into public.workouts (id, title, description, workout_type, segments, tags, is_public) values (
  '20000000-0000-0000-0000-000000000004',
  'Long Steady Intervals',
  'Four 10-minute blocks with short breaks. Sustained aerobic volume.',
  'variable_intervals',
  '[{"duration_type":"time","duration_value":300,"target_intensity":60,"target_watts":null,"target_stroke_rate":20,"target_hr_zone":1},{"duration_type":"time","duration_value":600,"target_intensity":70,"target_watts":null,"target_stroke_rate":22,"target_hr_zone":1},{"duration_type":"time","duration_value":120,"target_intensity":null,"target_watts":null,"target_stroke_rate":null,"target_hr_zone":null,"is_rest":true},{"duration_type":"time","duration_value":600,"target_intensity":70,"target_watts":null,"target_stroke_rate":22,"target_hr_zone":1},{"duration_type":"time","duration_value":120,"target_intensity":null,"target_watts":null,"target_stroke_rate":null,"target_hr_zone":null,"is_rest":true},{"duration_type":"time","duration_value":600,"target_intensity":70,"target_watts":null,"target_stroke_rate":22,"target_hr_zone":1},{"duration_type":"time","duration_value":120,"target_intensity":null,"target_watts":null,"target_stroke_rate":null,"target_hr_zone":null,"is_rest":true},{"duration_type":"time","duration_value":600,"target_intensity":70,"target_watts":null,"target_stroke_rate":22,"target_hr_zone":1},{"duration_type":"time","duration_value":300,"target_intensity":60,"target_watts":null,"target_stroke_rate":20,"target_hr_zone":1}]'::jsonb,
  '{aerobic,intervals,long}',
  true
);

insert into public.workouts (id, title, description, workout_type, segments, tags, is_public) values (
  '20000000-0000-0000-0000-000000000003',
  'Negative Split 30',
  'Start easy, finish stronger. Build into the second half.',
  'variable_intervals',
  '[{"duration_type":"time","duration_value":300,"target_intensity":60,"target_watts":null,"target_stroke_rate":20,"target_hr_zone":1},{"duration_type":"time","duration_value":900,"target_intensity":66,"target_watts":null,"target_stroke_rate":20,"target_hr_zone":1},{"duration_type":"time","duration_value":600,"target_intensity":74,"target_watts":null,"target_stroke_rate":22,"target_hr_zone":1},{"duration_type":"time","duration_value":300,"target_intensity":60,"target_watts":null,"target_stroke_rate":20,"target_hr_zone":1}]'::jsonb,
  '{aerobic,negative-split}',
  true
);

insert into public.workouts (id, title, description, workout_type, segments, tags, is_public) values (
  '20000000-0000-0000-0000-000000000009',
  'Rate Pyramid Steady',
  'Rate pyramid at constant aerobic intensity.',
  'variable_intervals',
  '[{"duration_type":"time","duration_value":300,"target_intensity":60,"target_watts":null,"target_stroke_rate":20,"target_hr_zone":1},{"duration_type":"time","duration_value":300,"target_intensity":70,"target_watts":null,"target_stroke_rate":18,"target_hr_zone":1},{"duration_type":"time","duration_value":300,"target_intensity":70,"target_watts":null,"target_stroke_rate":20,"target_hr_zone":1},{"duration_type":"time","duration_value":300,"target_intensity":70,"target_watts":null,"target_stroke_rate":22,"target_hr_zone":1},{"duration_type":"time","duration_value":300,"target_intensity":70,"target_watts":null,"target_stroke_rate":24,"target_hr_zone":1},{"duration_type":"time","duration_value":300,"target_intensity":70,"target_watts":null,"target_stroke_rate":22,"target_hr_zone":1},{"duration_type":"time","duration_value":300,"target_intensity":70,"target_watts":null,"target_stroke_rate":20,"target_hr_zone":1},{"duration_type":"time","duration_value":300,"target_intensity":60,"target_watts":null,"target_stroke_rate":20,"target_hr_zone":1}]'::jsonb,
  '{aerobic,pyramid,rate}',
  true
);

insert into public.workouts (id, title, description, workout_type, segments, tags, is_public) values (
  '20000000-0000-0000-0000-000000000002',
  'Rate Shift Steady',
  'Same pace, different rates. Feel how rate affects the stroke.',
  'variable_intervals',
  '[{"duration_type":"time","duration_value":300,"target_intensity":60,"target_watts":null,"target_stroke_rate":20,"target_hr_zone":1},{"duration_type":"time","duration_value":600,"target_intensity":70,"target_watts":null,"target_stroke_rate":18,"target_hr_zone":1},{"duration_type":"time","duration_value":600,"target_intensity":70,"target_watts":null,"target_stroke_rate":22,"target_hr_zone":1},{"duration_type":"time","duration_value":600,"target_intensity":70,"target_watts":null,"target_stroke_rate":20,"target_hr_zone":1},{"duration_type":"time","duration_value":300,"target_intensity":60,"target_watts":null,"target_stroke_rate":20,"target_hr_zone":1}]'::jsonb,
  '{aerobic,steady-state,rate-shift}',
  true
);

insert into public.workouts (id, title, description, workout_type, segments, tags, is_public) values (
  '20000000-0000-0000-0000-000000000001',
  'Steady State 40',
  '30 minutes of steady aerobic work. The bread and butter of training.',
  'variable_intervals',
  '[{"duration_type":"time","duration_value":300,"target_intensity":60,"target_watts":null,"target_stroke_rate":20,"target_hr_zone":1},{"duration_type":"time","duration_value":1800,"target_intensity":70,"target_watts":null,"target_stroke_rate":22,"target_hr_zone":1},{"duration_type":"time","duration_value":300,"target_intensity":60,"target_watts":null,"target_stroke_rate":20,"target_hr_zone":1}]'::jsonb,
  '{aerobic,steady-state,endurance}',
  true
);

insert into public.workouts (id, title, description, workout_type, segments, tags, is_public) values (
  '20000000-0000-0000-0000-000000000006',
  'Steady State 50',
  'Long aerobic session. Keep it comfortable for the full 40 minutes.',
  'variable_intervals',
  '[{"duration_type":"time","duration_value":300,"target_intensity":60,"target_watts":null,"target_stroke_rate":20,"target_hr_zone":1},{"duration_type":"time","duration_value":2400,"target_intensity":70,"target_watts":null,"target_stroke_rate":22,"target_hr_zone":1},{"duration_type":"time","duration_value":300,"target_intensity":60,"target_watts":null,"target_stroke_rate":20,"target_hr_zone":1}]'::jsonb,
  '{aerobic,steady-state,long}',
  true
);

insert into public.workouts (id, title, description, workout_type, segments, tags, is_public) values (
  '20000000-0000-0000-0000-00000000000a',
  'Two-Pace Aerobic',
  'Alternate moderate and easy aerobic blocks.',
  'variable_intervals',
  '[{"duration_type":"time","duration_value":300,"target_intensity":60,"target_watts":null,"target_stroke_rate":20,"target_hr_zone":1},{"duration_type":"time","duration_value":300,"target_intensity":66,"target_watts":null,"target_stroke_rate":20,"target_hr_zone":1},{"duration_type":"time","duration_value":300,"target_intensity":74,"target_watts":null,"target_stroke_rate":22,"target_hr_zone":1},{"duration_type":"time","duration_value":300,"target_intensity":66,"target_watts":null,"target_stroke_rate":20,"target_hr_zone":1},{"duration_type":"time","duration_value":300,"target_intensity":74,"target_watts":null,"target_stroke_rate":22,"target_hr_zone":1},{"duration_type":"time","duration_value":300,"target_intensity":66,"target_watts":null,"target_stroke_rate":20,"target_hr_zone":1},{"duration_type":"time","duration_value":300,"target_intensity":74,"target_watts":null,"target_stroke_rate":22,"target_hr_zone":1},{"duration_type":"time","duration_value":300,"target_intensity":66,"target_watts":null,"target_stroke_rate":20,"target_hr_zone":1},{"duration_type":"time","duration_value":300,"target_intensity":74,"target_watts":null,"target_stroke_rate":22,"target_hr_zone":1},{"duration_type":"time","duration_value":300,"target_intensity":60,"target_watts":null,"target_stroke_rate":20,"target_hr_zone":1}]'::jsonb,
  '{aerobic,steady-state}',
  true
);
