-- Migration: Sync all system workout segments to match seed.sql
-- Replaces any remaining compact/repeat-based segments with fully expanded versions
-- and applies corrected pace targets.

-- 2K Test
UPDATE public.workouts SET segments = '[{"type":"work","duration_type":"distance","duration_value":2000,"target_split":null,"target_stroke_rate":{"min":28,"max":36},"target_hr_zone":null}]'::jsonb WHERE id = 'a0000000-0000-0000-0000-000000000001';

-- 5K Test
UPDATE public.workouts SET segments = '[{"type":"work","duration_type":"distance","duration_value":5000,"target_split":null,"target_stroke_rate":{"min":24,"max":30},"target_hr_zone":null}]'::jsonb WHERE id = 'a0000000-0000-0000-0000-000000000002';

-- 30 Minute Steady State
UPDATE public.workouts SET segments = '[{"type":"work","duration_type":"time","duration_value":1800,"target_split":{"min":1300,"max":1500},"target_stroke_rate":{"min":18,"max":22},"target_hr_zone":2}]'::jsonb WHERE id = 'a0000000-0000-0000-0000-000000000003';

-- 10 x 500m
UPDATE public.workouts SET segments = '[{"type":"work","duration_type":"distance","duration_value":500,"target_split":{"min":1150,"max":1300},"target_stroke_rate":{"min":26,"max":30},"target_hr_zone":4},{"type":"rest","duration_type":"time","duration_value":60,"target_split":null,"target_stroke_rate":null,"target_hr_zone":null},{"type":"work","duration_type":"distance","duration_value":500,"target_split":{"min":1150,"max":1300},"target_stroke_rate":{"min":26,"max":30},"target_hr_zone":4},{"type":"rest","duration_type":"time","duration_value":60,"target_split":null,"target_stroke_rate":null,"target_hr_zone":null},{"type":"work","duration_type":"distance","duration_value":500,"target_split":{"min":1150,"max":1300},"target_stroke_rate":{"min":26,"max":30},"target_hr_zone":4},{"type":"rest","duration_type":"time","duration_value":60,"target_split":null,"target_stroke_rate":null,"target_hr_zone":null},{"type":"work","duration_type":"distance","duration_value":500,"target_split":{"min":1150,"max":1300},"target_stroke_rate":{"min":26,"max":30},"target_hr_zone":4},{"type":"rest","duration_type":"time","duration_value":60,"target_split":null,"target_stroke_rate":null,"target_hr_zone":null},{"type":"work","duration_type":"distance","duration_value":500,"target_split":{"min":1150,"max":1300},"target_stroke_rate":{"min":26,"max":30},"target_hr_zone":4},{"type":"rest","duration_type":"time","duration_value":60,"target_split":null,"target_stroke_rate":null,"target_hr_zone":null},{"type":"work","duration_type":"distance","duration_value":500,"target_split":{"min":1150,"max":1300},"target_stroke_rate":{"min":26,"max":30},"target_hr_zone":4},{"type":"rest","duration_type":"time","duration_value":60,"target_split":null,"target_stroke_rate":null,"target_hr_zone":null},{"type":"work","duration_type":"distance","duration_value":500,"target_split":{"min":1150,"max":1300},"target_stroke_rate":{"min":26,"max":30},"target_hr_zone":4},{"type":"rest","duration_type":"time","duration_value":60,"target_split":null,"target_stroke_rate":null,"target_hr_zone":null},{"type":"work","duration_type":"distance","duration_value":500,"target_split":{"min":1150,"max":1300},"target_stroke_rate":{"min":26,"max":30},"target_hr_zone":4},{"type":"rest","duration_type":"time","duration_value":60,"target_split":null,"target_stroke_rate":null,"target_hr_zone":null},{"type":"work","duration_type":"distance","duration_value":500,"target_split":{"min":1150,"max":1300},"target_stroke_rate":{"min":26,"max":30},"target_hr_zone":4},{"type":"rest","duration_type":"time","duration_value":60,"target_split":null,"target_stroke_rate":null,"target_hr_zone":null}]'::jsonb WHERE id = 'a0000000-0000-0000-0000-000000000004';

-- 20-Minute FTP Test
UPDATE public.workouts SET segments = '[{"type":"work","duration_type":"time","duration_value":1200,"target_split":null,"target_stroke_rate":{"min":24,"max":30},"target_hr_zone":null}]'::jsonb WHERE id = 'a0000000-0000-0000-0000-000000000005';

-- Ramp FTP Test
UPDATE public.workouts SET segments = '[{"type":"warmup","duration_type":"time","duration_value":120,"target_split":{"min":1500,"max":1600},"target_stroke_rate":{"min":18,"max":22},"target_hr_zone":1},{"type":"work","duration_type":"time","duration_value":60,"target_split":{"min":1740,"max":1800},"target_stroke_rate":{"min":18,"max":22}},{"type":"work","duration_type":"time","duration_value":60,"target_split":{"min":1580,"max":1640},"target_stroke_rate":{"min":20,"max":24}},{"type":"work","duration_type":"time","duration_value":60,"target_split":{"min":1460,"max":1520},"target_stroke_rate":{"min":20,"max":24}},{"type":"work","duration_type":"time","duration_value":60,"target_split":{"min":1370,"max":1430},"target_stroke_rate":{"min":22,"max":26}},{"type":"work","duration_type":"time","duration_value":60,"target_split":{"min":1290,"max":1350},"target_stroke_rate":{"min":22,"max":26}},{"type":"work","duration_type":"time","duration_value":60,"target_split":{"min":1230,"max":1280},"target_stroke_rate":{"min":24,"max":28}},{"type":"work","duration_type":"time","duration_value":60,"target_split":{"min":1170,"max":1220},"target_stroke_rate":{"min":24,"max":28}},{"type":"work","duration_type":"time","duration_value":60,"target_split":{"min":1120,"max":1170},"target_stroke_rate":{"min":26,"max":30}},{"type":"work","duration_type":"time","duration_value":60,"target_split":{"min":1080,"max":1120},"target_stroke_rate":{"min":26,"max":30}},{"type":"work","duration_type":"time","duration_value":60,"target_split":{"min":1040,"max":1080},"target_stroke_rate":{"min":28,"max":32}},{"type":"work","duration_type":"time","duration_value":60,"target_split":{"min":1000,"max":1040},"target_stroke_rate":{"min":28,"max":32}},{"type":"work","duration_type":"time","duration_value":60,"target_split":{"min":970,"max":1000},"target_stroke_rate":{"min":30,"max":34}},{"type":"work","duration_type":"time","duration_value":60,"target_split":{"min":940,"max":970},"target_stroke_rate":{"min":30,"max":34}},{"type":"work","duration_type":"time","duration_value":60,"target_split":{"min":910,"max":940},"target_stroke_rate":{"min":32,"max":36}},{"type":"work","duration_type":"time","duration_value":60,"target_split":{"min":880,"max":910},"target_stroke_rate":{"min":32,"max":38}}]'::jsonb WHERE id = 'a0000000-0000-0000-0000-000000000006';

-- Pete Plan — Week 1 Monday
UPDATE public.workouts SET segments = '[{"type":"work","duration_type":"distance","duration_value":5000,"target_split":{"min":1300,"max":1500},"target_stroke_rate":{"min":20,"max":24},"target_hr_zone":3}]'::jsonb WHERE id = 'b0000000-0000-0000-0000-000000000001';

-- Pete Plan — Week 1 Wednesday
UPDATE public.workouts SET segments = '[{"type":"work","duration_type":"distance","duration_value":500,"target_split":{"min":1150,"max":1300},"target_stroke_rate":{"min":26,"max":32},"target_hr_zone":4},{"type":"rest","duration_type":"time","duration_value":210,"target_split":null,"target_stroke_rate":null,"target_hr_zone":null},{"type":"work","duration_type":"distance","duration_value":500,"target_split":{"min":1150,"max":1300},"target_stroke_rate":{"min":26,"max":32},"target_hr_zone":4},{"type":"rest","duration_type":"time","duration_value":210,"target_split":null,"target_stroke_rate":null,"target_hr_zone":null},{"type":"work","duration_type":"distance","duration_value":500,"target_split":{"min":1150,"max":1300},"target_stroke_rate":{"min":26,"max":32},"target_hr_zone":4},{"type":"rest","duration_type":"time","duration_value":210,"target_split":null,"target_stroke_rate":null,"target_hr_zone":null},{"type":"work","duration_type":"distance","duration_value":500,"target_split":{"min":1150,"max":1300},"target_stroke_rate":{"min":26,"max":32},"target_hr_zone":4},{"type":"rest","duration_type":"time","duration_value":210,"target_split":null,"target_stroke_rate":null,"target_hr_zone":null},{"type":"work","duration_type":"distance","duration_value":500,"target_split":{"min":1150,"max":1300},"target_stroke_rate":{"min":26,"max":32},"target_hr_zone":4},{"type":"rest","duration_type":"time","duration_value":210,"target_split":null,"target_stroke_rate":null,"target_hr_zone":null},{"type":"work","duration_type":"distance","duration_value":500,"target_split":{"min":1150,"max":1300},"target_stroke_rate":{"min":26,"max":32},"target_hr_zone":4},{"type":"rest","duration_type":"time","duration_value":210,"target_split":null,"target_stroke_rate":null,"target_hr_zone":null},{"type":"work","duration_type":"distance","duration_value":500,"target_split":{"min":1150,"max":1300},"target_stroke_rate":{"min":26,"max":32},"target_hr_zone":4},{"type":"rest","duration_type":"time","duration_value":210,"target_split":null,"target_stroke_rate":null,"target_hr_zone":null},{"type":"work","duration_type":"distance","duration_value":500,"target_split":{"min":1150,"max":1300},"target_stroke_rate":{"min":26,"max":32},"target_hr_zone":4},{"type":"rest","duration_type":"time","duration_value":210,"target_split":null,"target_stroke_rate":null,"target_hr_zone":null}]'::jsonb WHERE id = 'b0000000-0000-0000-0000-000000000002';

-- Pete Plan — Week 1 Friday
UPDATE public.workouts SET segments = '[{"type":"work","duration_type":"time","duration_value":1200,"target_split":{"min":1200,"max":1400},"target_stroke_rate":{"min":18,"max":22},"target_hr_zone":2}]'::jsonb WHERE id = 'b0000000-0000-0000-0000-000000000003';

-- Wolverine Plan — WOD 1
UPDATE public.workouts SET segments = '[{"type":"work","duration_type":"distance","duration_value":2000,"target_split":{"min":1150,"max":1300},"target_stroke_rate":{"min":20,"max":22},"target_hr_zone":3},{"type":"rest","duration_type":"time","duration_value":300,"target_split":null,"target_stroke_rate":null,"target_hr_zone":null},{"type":"work","duration_type":"distance","duration_value":2000,"target_split":{"min":1150,"max":1300},"target_stroke_rate":{"min":20,"max":22},"target_hr_zone":3},{"type":"rest","duration_type":"time","duration_value":300,"target_split":null,"target_stroke_rate":null,"target_hr_zone":null},{"type":"work","duration_type":"distance","duration_value":2000,"target_split":{"min":1150,"max":1300},"target_stroke_rate":{"min":20,"max":22},"target_hr_zone":3},{"type":"rest","duration_type":"time","duration_value":300,"target_split":null,"target_stroke_rate":null,"target_hr_zone":null},{"type":"work","duration_type":"distance","duration_value":2000,"target_split":{"min":1150,"max":1300},"target_stroke_rate":{"min":20,"max":22},"target_hr_zone":3},{"type":"rest","duration_type":"time","duration_value":300,"target_split":null,"target_stroke_rate":null,"target_hr_zone":null}]'::jsonb WHERE id = 'c0000000-0000-0000-0000-000000000001';

-- British Rowing — Beginner Session 1
UPDATE public.workouts SET segments = '[{"type":"warmup","duration_type":"time","duration_value":180,"target_split":{"min":1400,"max":1600},"target_stroke_rate":{"min":16,"max":20},"target_hr_zone":1},{"type":"work","duration_type":"time","duration_value":180,"target_split":{"min":1300,"max":1500},"target_stroke_rate":{"min":20,"max":24},"target_hr_zone":3},{"type":"rest","duration_type":"time","duration_value":60,"target_split":null,"target_stroke_rate":null,"target_hr_zone":null},{"type":"work","duration_type":"time","duration_value":180,"target_split":{"min":1300,"max":1500},"target_stroke_rate":{"min":20,"max":24},"target_hr_zone":3},{"type":"rest","duration_type":"time","duration_value":60,"target_split":null,"target_stroke_rate":null,"target_hr_zone":null},{"type":"work","duration_type":"time","duration_value":180,"target_split":{"min":1300,"max":1500},"target_stroke_rate":{"min":20,"max":24},"target_hr_zone":3},{"type":"rest","duration_type":"time","duration_value":60,"target_split":null,"target_stroke_rate":null,"target_hr_zone":null},{"type":"work","duration_type":"time","duration_value":180,"target_split":{"min":1300,"max":1500},"target_stroke_rate":{"min":20,"max":24},"target_hr_zone":3},{"type":"rest","duration_type":"time","duration_value":60,"target_split":null,"target_stroke_rate":null,"target_hr_zone":null},{"type":"work","duration_type":"time","duration_value":180,"target_split":{"min":1300,"max":1500},"target_stroke_rate":{"min":20,"max":24},"target_hr_zone":3},{"type":"rest","duration_type":"time","duration_value":60,"target_split":null,"target_stroke_rate":null,"target_hr_zone":null},{"type":"cooldown","duration_type":"time","duration_value":180,"target_split":{"min":1400,"max":1600},"target_stroke_rate":{"min":16,"max":20},"target_hr_zone":1}]'::jsonb WHERE id = 'd0000000-0000-0000-0000-000000000001';

-- Pete Plan — Wk2 Mon
UPDATE public.workouts SET segments = '[{"type":"work","duration_type":"distance","duration_value":5500,"target_split":{"min":1300,"max":1500},"target_stroke_rate":{"min":20,"max":24},"target_hr_zone":3}]'::jsonb WHERE id = 'e0000000-0000-0000-0001-000000000001';

-- Pete Plan — Wk3 Mon
UPDATE public.workouts SET segments = '[{"type":"work","duration_type":"distance","duration_value":6000,"target_split":{"min":1300,"max":1500},"target_stroke_rate":{"min":20,"max":24},"target_hr_zone":3}]'::jsonb WHERE id = 'e0000000-0000-0000-0001-000000000002';

-- Pete Plan — Wk4 Mon
UPDATE public.workouts SET segments = '[{"type":"work","duration_type":"distance","duration_value":6500,"target_split":{"min":1300,"max":1500},"target_stroke_rate":{"min":20,"max":24},"target_hr_zone":3}]'::jsonb WHERE id = 'e0000000-0000-0000-0001-000000000003';

-- Pete Plan — Wk5 Mon
UPDATE public.workouts SET segments = '[{"type":"work","duration_type":"distance","duration_value":7000,"target_split":{"min":1300,"max":1500},"target_stroke_rate":{"min":20,"max":24},"target_hr_zone":3}]'::jsonb WHERE id = 'e0000000-0000-0000-0001-000000000004';

-- Pete Plan — Wk6 Mon
UPDATE public.workouts SET segments = '[{"type":"work","duration_type":"distance","duration_value":7500,"target_split":{"min":1300,"max":1500},"target_stroke_rate":{"min":20,"max":24},"target_hr_zone":3}]'::jsonb WHERE id = 'e0000000-0000-0000-0001-000000000005';

-- Pete Plan — Wk2 Wed
UPDATE public.workouts SET segments = '[{"type":"work","duration_type":"distance","duration_value":750,"target_split":{"min":1150,"max":1300},"target_stroke_rate":{"min":26,"max":32},"target_hr_zone":4},{"type":"rest","duration_type":"time","duration_value":180,"target_split":null,"target_stroke_rate":null,"target_hr_zone":null},{"type":"work","duration_type":"distance","duration_value":750,"target_split":{"min":1150,"max":1300},"target_stroke_rate":{"min":26,"max":32},"target_hr_zone":4},{"type":"rest","duration_type":"time","duration_value":180,"target_split":null,"target_stroke_rate":null,"target_hr_zone":null},{"type":"work","duration_type":"distance","duration_value":750,"target_split":{"min":1150,"max":1300},"target_stroke_rate":{"min":26,"max":32},"target_hr_zone":4},{"type":"rest","duration_type":"time","duration_value":180,"target_split":null,"target_stroke_rate":null,"target_hr_zone":null},{"type":"work","duration_type":"distance","duration_value":750,"target_split":{"min":1150,"max":1300},"target_stroke_rate":{"min":26,"max":32},"target_hr_zone":4},{"type":"rest","duration_type":"time","duration_value":180,"target_split":null,"target_stroke_rate":null,"target_hr_zone":null},{"type":"work","duration_type":"distance","duration_value":750,"target_split":{"min":1150,"max":1300},"target_stroke_rate":{"min":26,"max":32},"target_hr_zone":4},{"type":"rest","duration_type":"time","duration_value":180,"target_split":null,"target_stroke_rate":null,"target_hr_zone":null},{"type":"work","duration_type":"distance","duration_value":750,"target_split":{"min":1150,"max":1300},"target_stroke_rate":{"min":26,"max":32},"target_hr_zone":4},{"type":"rest","duration_type":"time","duration_value":180,"target_split":null,"target_stroke_rate":null,"target_hr_zone":null}]'::jsonb WHERE id = 'e0000000-0000-0000-0002-000000000001';

-- Pete Plan — Wk3 Wed
UPDATE public.workouts SET segments = '[{"type":"work","duration_type":"distance","duration_value":1000,"target_split":{"min":1150,"max":1300},"target_stroke_rate":{"min":26,"max":32},"target_hr_zone":4},{"type":"rest","duration_type":"time","duration_value":180,"target_split":null,"target_stroke_rate":null,"target_hr_zone":null},{"type":"work","duration_type":"distance","duration_value":1000,"target_split":{"min":1150,"max":1300},"target_stroke_rate":{"min":26,"max":32},"target_hr_zone":4},{"type":"rest","duration_type":"time","duration_value":180,"target_split":null,"target_stroke_rate":null,"target_hr_zone":null},{"type":"work","duration_type":"distance","duration_value":1000,"target_split":{"min":1150,"max":1300},"target_stroke_rate":{"min":26,"max":32},"target_hr_zone":4},{"type":"rest","duration_type":"time","duration_value":180,"target_split":null,"target_stroke_rate":null,"target_hr_zone":null},{"type":"work","duration_type":"distance","duration_value":1000,"target_split":{"min":1150,"max":1300},"target_stroke_rate":{"min":26,"max":32},"target_hr_zone":4},{"type":"rest","duration_type":"time","duration_value":180,"target_split":null,"target_stroke_rate":null,"target_hr_zone":null}]'::jsonb WHERE id = 'e0000000-0000-0000-0002-000000000002';

-- Pete Plan — Wk4 Wed
UPDATE public.workouts SET segments = '[{"type":"work","duration_type":"distance","duration_value":500,"target_split":{"min":1150,"max":1300},"target_stroke_rate":{"min":26,"max":32},"target_hr_zone":4},{"type":"rest","duration_type":"time","duration_value":180,"target_split":null,"target_stroke_rate":null,"target_hr_zone":null},{"type":"work","duration_type":"distance","duration_value":500,"target_split":{"min":1150,"max":1300},"target_stroke_rate":{"min":26,"max":32},"target_hr_zone":4},{"type":"rest","duration_type":"time","duration_value":180,"target_split":null,"target_stroke_rate":null,"target_hr_zone":null},{"type":"work","duration_type":"distance","duration_value":500,"target_split":{"min":1150,"max":1300},"target_stroke_rate":{"min":26,"max":32},"target_hr_zone":4},{"type":"rest","duration_type":"time","duration_value":180,"target_split":null,"target_stroke_rate":null,"target_hr_zone":null},{"type":"work","duration_type":"distance","duration_value":500,"target_split":{"min":1150,"max":1300},"target_stroke_rate":{"min":26,"max":32},"target_hr_zone":4},{"type":"rest","duration_type":"time","duration_value":180,"target_split":null,"target_stroke_rate":null,"target_hr_zone":null},{"type":"work","duration_type":"distance","duration_value":500,"target_split":{"min":1150,"max":1300},"target_stroke_rate":{"min":26,"max":32},"target_hr_zone":4},{"type":"rest","duration_type":"time","duration_value":180,"target_split":null,"target_stroke_rate":null,"target_hr_zone":null},{"type":"work","duration_type":"distance","duration_value":500,"target_split":{"min":1150,"max":1300},"target_stroke_rate":{"min":26,"max":32},"target_hr_zone":4},{"type":"rest","duration_type":"time","duration_value":180,"target_split":null,"target_stroke_rate":null,"target_hr_zone":null},{"type":"work","duration_type":"distance","duration_value":500,"target_split":{"min":1150,"max":1300},"target_stroke_rate":{"min":26,"max":32},"target_hr_zone":4},{"type":"rest","duration_type":"time","duration_value":180,"target_split":null,"target_stroke_rate":null,"target_hr_zone":null},{"type":"work","duration_type":"distance","duration_value":500,"target_split":{"min":1150,"max":1300},"target_stroke_rate":{"min":26,"max":32},"target_hr_zone":4},{"type":"rest","duration_type":"time","duration_value":180,"target_split":null,"target_stroke_rate":null,"target_hr_zone":null}]'::jsonb WHERE id = 'e0000000-0000-0000-0002-000000000003';

-- Pete Plan — Wk5 Wed
UPDATE public.workouts SET segments = '[{"type":"work","duration_type":"distance","duration_value":750,"target_split":{"min":1150,"max":1300},"target_stroke_rate":{"min":26,"max":32},"target_hr_zone":4},{"type":"rest","duration_type":"time","duration_value":180,"target_split":null,"target_stroke_rate":null,"target_hr_zone":null},{"type":"work","duration_type":"distance","duration_value":750,"target_split":{"min":1150,"max":1300},"target_stroke_rate":{"min":26,"max":32},"target_hr_zone":4},{"type":"rest","duration_type":"time","duration_value":180,"target_split":null,"target_stroke_rate":null,"target_hr_zone":null},{"type":"work","duration_type":"distance","duration_value":750,"target_split":{"min":1150,"max":1300},"target_stroke_rate":{"min":26,"max":32},"target_hr_zone":4},{"type":"rest","duration_type":"time","duration_value":180,"target_split":null,"target_stroke_rate":null,"target_hr_zone":null},{"type":"work","duration_type":"distance","duration_value":750,"target_split":{"min":1150,"max":1300},"target_stroke_rate":{"min":26,"max":32},"target_hr_zone":4},{"type":"rest","duration_type":"time","duration_value":180,"target_split":null,"target_stroke_rate":null,"target_hr_zone":null},{"type":"work","duration_type":"distance","duration_value":750,"target_split":{"min":1150,"max":1300},"target_stroke_rate":{"min":26,"max":32},"target_hr_zone":4},{"type":"rest","duration_type":"time","duration_value":180,"target_split":null,"target_stroke_rate":null,"target_hr_zone":null},{"type":"work","duration_type":"distance","duration_value":750,"target_split":{"min":1150,"max":1300},"target_stroke_rate":{"min":26,"max":32},"target_hr_zone":4},{"type":"rest","duration_type":"time","duration_value":180,"target_split":null,"target_stroke_rate":null,"target_hr_zone":null}]'::jsonb WHERE id = 'e0000000-0000-0000-0002-000000000004';

-- Pete Plan — Wk6 Wed
UPDATE public.workouts SET segments = '[{"type":"work","duration_type":"distance","duration_value":1000,"target_split":{"min":1150,"max":1300},"target_stroke_rate":{"min":26,"max":32},"target_hr_zone":4},{"type":"rest","duration_type":"time","duration_value":180,"target_split":null,"target_stroke_rate":null,"target_hr_zone":null},{"type":"work","duration_type":"distance","duration_value":1000,"target_split":{"min":1150,"max":1300},"target_stroke_rate":{"min":26,"max":32},"target_hr_zone":4},{"type":"rest","duration_type":"time","duration_value":180,"target_split":null,"target_stroke_rate":null,"target_hr_zone":null},{"type":"work","duration_type":"distance","duration_value":1000,"target_split":{"min":1150,"max":1300},"target_stroke_rate":{"min":26,"max":32},"target_hr_zone":4},{"type":"rest","duration_type":"time","duration_value":180,"target_split":null,"target_stroke_rate":null,"target_hr_zone":null},{"type":"work","duration_type":"distance","duration_value":1000,"target_split":{"min":1150,"max":1300},"target_stroke_rate":{"min":26,"max":32},"target_hr_zone":4},{"type":"rest","duration_type":"time","duration_value":180,"target_split":null,"target_stroke_rate":null,"target_hr_zone":null}]'::jsonb WHERE id = 'e0000000-0000-0000-0002-000000000005';

-- Pete Plan — Wk2 Fri
UPDATE public.workouts SET segments = '[{"type":"work","duration_type":"time","duration_value":1320,"target_split":{"min":1200,"max":1400},"target_stroke_rate":{"min":18,"max":22},"target_hr_zone":2}]'::jsonb WHERE id = 'e0000000-0000-0000-0003-000000000001';

-- Pete Plan — Wk3 Fri
UPDATE public.workouts SET segments = '[{"type":"work","duration_type":"time","duration_value":1440,"target_split":{"min":1200,"max":1400},"target_stroke_rate":{"min":18,"max":22},"target_hr_zone":2}]'::jsonb WHERE id = 'e0000000-0000-0000-0003-000000000002';

-- Pete Plan — Wk4 Fri
UPDATE public.workouts SET segments = '[{"type":"work","duration_type":"time","duration_value":1200,"target_split":{"min":1200,"max":1400},"target_stroke_rate":{"min":18,"max":22},"target_hr_zone":2}]'::jsonb WHERE id = 'e0000000-0000-0000-0003-000000000003';

-- Pete Plan — Wk5 Fri
UPDATE public.workouts SET segments = '[{"type":"work","duration_type":"time","duration_value":1320,"target_split":{"min":1200,"max":1400},"target_stroke_rate":{"min":18,"max":22},"target_hr_zone":2}]'::jsonb WHERE id = 'e0000000-0000-0000-0003-000000000004';

-- Pete Plan — Wk6 Fri
UPDATE public.workouts SET segments = '[{"type":"work","duration_type":"time","duration_value":1440,"target_split":{"min":1200,"max":1400},"target_stroke_rate":{"min":18,"max":22},"target_hr_zone":2}]'::jsonb WHERE id = 'e0000000-0000-0000-0003-000000000005';

-- Return to Rowing — Wk1 Day 1
UPDATE public.workouts SET segments = '[{"type":"work","duration_type":"time","duration_value":600,"target_split":{"min":1300,"max":1600},"target_stroke_rate":{"min":16,"max":20},"target_hr_zone":1}]'::jsonb WHERE id = 'f0000000-0000-0000-0001-000000000001';

-- Return to Rowing — Wk1 Day 2
UPDATE public.workouts SET segments = '[{"type":"work","duration_type":"time","duration_value":180,"target_split":{"min":1200,"max":1400},"target_stroke_rate":{"min":20,"max":24},"target_hr_zone":2},{"type":"rest","duration_type":"time","duration_value":60,"target_split":null,"target_stroke_rate":null,"target_hr_zone":null},{"type":"work","duration_type":"time","duration_value":180,"target_split":{"min":1200,"max":1400},"target_stroke_rate":{"min":20,"max":24},"target_hr_zone":2},{"type":"rest","duration_type":"time","duration_value":60,"target_split":null,"target_stroke_rate":null,"target_hr_zone":null},{"type":"work","duration_type":"time","duration_value":180,"target_split":{"min":1200,"max":1400},"target_stroke_rate":{"min":20,"max":24},"target_hr_zone":2},{"type":"rest","duration_type":"time","duration_value":60,"target_split":null,"target_stroke_rate":null,"target_hr_zone":null}]'::jsonb WHERE id = 'f0000000-0000-0000-0001-000000000002';

-- Return to Rowing — Wk1 Day 3
UPDATE public.workouts SET segments = '[{"type":"work","duration_type":"time","duration_value":900,"target_split":{"min":1300,"max":1600},"target_stroke_rate":{"min":16,"max":20},"target_hr_zone":1}]'::jsonb WHERE id = 'f0000000-0000-0000-0001-000000000003';

-- Return to Rowing — Wk2 Day 1
UPDATE public.workouts SET segments = '[{"type":"work","duration_type":"time","duration_value":900,"target_split":{"min":1250,"max":1500},"target_stroke_rate":{"min":18,"max":22},"target_hr_zone":2}]'::jsonb WHERE id = 'f0000000-0000-0000-0002-000000000001';

-- Return to Rowing — Wk2 Day 2
UPDATE public.workouts SET segments = '[{"type":"work","duration_type":"time","duration_value":180,"target_split":{"min":1200,"max":1350},"target_stroke_rate":{"min":20,"max":24},"target_hr_zone":3},{"type":"rest","duration_type":"time","duration_value":60,"target_split":null,"target_stroke_rate":null,"target_hr_zone":null},{"type":"work","duration_type":"time","duration_value":180,"target_split":{"min":1200,"max":1350},"target_stroke_rate":{"min":20,"max":24},"target_hr_zone":3},{"type":"rest","duration_type":"time","duration_value":60,"target_split":null,"target_stroke_rate":null,"target_hr_zone":null},{"type":"work","duration_type":"time","duration_value":180,"target_split":{"min":1200,"max":1350},"target_stroke_rate":{"min":20,"max":24},"target_hr_zone":3},{"type":"rest","duration_type":"time","duration_value":60,"target_split":null,"target_stroke_rate":null,"target_hr_zone":null},{"type":"work","duration_type":"time","duration_value":180,"target_split":{"min":1200,"max":1350},"target_stroke_rate":{"min":20,"max":24},"target_hr_zone":3},{"type":"rest","duration_type":"time","duration_value":60,"target_split":null,"target_stroke_rate":null,"target_hr_zone":null},{"type":"work","duration_type":"time","duration_value":180,"target_split":{"min":1200,"max":1350},"target_stroke_rate":{"min":20,"max":24},"target_hr_zone":3},{"type":"rest","duration_type":"time","duration_value":60,"target_split":null,"target_stroke_rate":null,"target_hr_zone":null}]'::jsonb WHERE id = 'f0000000-0000-0000-0002-000000000002';

-- Return to Rowing — Wk2 Day 3
UPDATE public.workouts SET segments = '[{"type":"work","duration_type":"time","duration_value":1200,"target_split":{"min":1250,"max":1500},"target_stroke_rate":{"min":18,"max":22},"target_hr_zone":2}]'::jsonb WHERE id = 'f0000000-0000-0000-0002-000000000003';

-- Return to Rowing — Wk3 Day 1
UPDATE public.workouts SET segments = '[{"type":"work","duration_type":"time","duration_value":1200,"target_split":{"min":1200,"max":1400},"target_stroke_rate":{"min":18,"max":22},"target_hr_zone":2}]'::jsonb WHERE id = 'f0000000-0000-0000-0003-000000000001';

-- Return to Rowing — Wk3 Day 2
UPDATE public.workouts SET segments = '[{"type":"work","duration_type":"distance","duration_value":500,"target_split":{"min":1150,"max":1300},"target_stroke_rate":{"min":24,"max":28},"target_hr_zone":3},{"type":"rest","duration_type":"time","duration_value":90,"target_split":null,"target_stroke_rate":null,"target_hr_zone":null},{"type":"work","duration_type":"distance","duration_value":500,"target_split":{"min":1150,"max":1300},"target_stroke_rate":{"min":24,"max":28},"target_hr_zone":3},{"type":"rest","duration_type":"time","duration_value":90,"target_split":null,"target_stroke_rate":null,"target_hr_zone":null},{"type":"work","duration_type":"distance","duration_value":500,"target_split":{"min":1150,"max":1300},"target_stroke_rate":{"min":24,"max":28},"target_hr_zone":3},{"type":"rest","duration_type":"time","duration_value":90,"target_split":null,"target_stroke_rate":null,"target_hr_zone":null},{"type":"work","duration_type":"distance","duration_value":500,"target_split":{"min":1150,"max":1300},"target_stroke_rate":{"min":24,"max":28},"target_hr_zone":3},{"type":"rest","duration_type":"time","duration_value":90,"target_split":null,"target_stroke_rate":null,"target_hr_zone":null},{"type":"work","duration_type":"distance","duration_value":500,"target_split":{"min":1150,"max":1300},"target_stroke_rate":{"min":24,"max":28},"target_hr_zone":3},{"type":"rest","duration_type":"time","duration_value":90,"target_split":null,"target_stroke_rate":null,"target_hr_zone":null},{"type":"work","duration_type":"distance","duration_value":500,"target_split":{"min":1150,"max":1300},"target_stroke_rate":{"min":24,"max":28},"target_hr_zone":3},{"type":"rest","duration_type":"time","duration_value":90,"target_split":null,"target_stroke_rate":null,"target_hr_zone":null}]'::jsonb WHERE id = 'f0000000-0000-0000-0003-000000000002';

-- Return to Rowing — Wk3 Day 3
UPDATE public.workouts SET segments = '[{"type":"work","duration_type":"time","duration_value":1500,"target_split":{"min":1250,"max":1500},"target_stroke_rate":{"min":18,"max":22},"target_hr_zone":2}]'::jsonb WHERE id = 'f0000000-0000-0000-0003-000000000003';

-- Return to Rowing — Wk4 Day 1
UPDATE public.workouts SET segments = '[{"type":"work","duration_type":"time","duration_value":1500,"target_split":{"min":1200,"max":1350},"target_stroke_rate":{"min":18,"max":22},"target_hr_zone":2}]'::jsonb WHERE id = 'f0000000-0000-0000-0004-000000000001';

-- Return to Rowing — Wk4 Day 2
UPDATE public.workouts SET segments = '[{"type":"work","duration_type":"distance","duration_value":500,"target_split":{"min":1050,"max":1200},"target_stroke_rate":{"min":26,"max":30},"target_hr_zone":4},{"type":"rest","duration_type":"time","duration_value":90,"target_split":null,"target_stroke_rate":null,"target_hr_zone":null},{"type":"work","duration_type":"distance","duration_value":500,"target_split":{"min":1050,"max":1200},"target_stroke_rate":{"min":26,"max":30},"target_hr_zone":4},{"type":"rest","duration_type":"time","duration_value":90,"target_split":null,"target_stroke_rate":null,"target_hr_zone":null},{"type":"work","duration_type":"distance","duration_value":500,"target_split":{"min":1050,"max":1200},"target_stroke_rate":{"min":26,"max":30},"target_hr_zone":4},{"type":"rest","duration_type":"time","duration_value":90,"target_split":null,"target_stroke_rate":null,"target_hr_zone":null},{"type":"work","duration_type":"distance","duration_value":500,"target_split":{"min":1050,"max":1200},"target_stroke_rate":{"min":26,"max":30},"target_hr_zone":4},{"type":"rest","duration_type":"time","duration_value":90,"target_split":null,"target_stroke_rate":null,"target_hr_zone":null},{"type":"work","duration_type":"distance","duration_value":500,"target_split":{"min":1050,"max":1200},"target_stroke_rate":{"min":26,"max":30},"target_hr_zone":4},{"type":"rest","duration_type":"time","duration_value":90,"target_split":null,"target_stroke_rate":null,"target_hr_zone":null},{"type":"work","duration_type":"distance","duration_value":500,"target_split":{"min":1050,"max":1200},"target_stroke_rate":{"min":26,"max":30},"target_hr_zone":4},{"type":"rest","duration_type":"time","duration_value":90,"target_split":null,"target_stroke_rate":null,"target_hr_zone":null},{"type":"work","duration_type":"distance","duration_value":500,"target_split":{"min":1050,"max":1200},"target_stroke_rate":{"min":26,"max":30},"target_hr_zone":4},{"type":"rest","duration_type":"time","duration_value":90,"target_split":null,"target_stroke_rate":null,"target_hr_zone":null},{"type":"work","duration_type":"distance","duration_value":500,"target_split":{"min":1050,"max":1200},"target_stroke_rate":{"min":26,"max":30},"target_hr_zone":4},{"type":"rest","duration_type":"time","duration_value":90,"target_split":null,"target_stroke_rate":null,"target_hr_zone":null}]'::jsonb WHERE id = 'f0000000-0000-0000-0004-000000000002';

-- FTP Builder — Wk1 Steady State
UPDATE public.workouts SET segments = '[{"type":"work","duration_type":"time","duration_value":1800,"target_split":{"min":1200,"max":1400},"target_stroke_rate":{"min":18,"max":22},"target_hr_zone":2}]'::jsonb WHERE id = 'e1000000-0000-0000-0001-000000000002';

-- FTP Builder — Wk1 Recovery
UPDATE public.workouts SET segments = '[{"type":"work","duration_type":"time","duration_value":1200,"target_split":{"min":1350,"max":1600},"target_stroke_rate":{"min":16,"max":20},"target_hr_zone":1}]'::jsonb WHERE id = 'e1000000-0000-0000-0001-000000000003';

-- FTP Builder — Wk2 Threshold
UPDATE public.workouts SET segments = '[{"type":"work","duration_type":"time","duration_value":300,"target_split":{"min":1100,"max":1200},"target_stroke_rate":{"min":24,"max":28},"target_hr_zone":4},{"type":"rest","duration_type":"time","duration_value":120,"target_split":null,"target_stroke_rate":null,"target_hr_zone":null},{"type":"work","duration_type":"time","duration_value":300,"target_split":{"min":1100,"max":1200},"target_stroke_rate":{"min":24,"max":28},"target_hr_zone":4},{"type":"rest","duration_type":"time","duration_value":120,"target_split":null,"target_stroke_rate":null,"target_hr_zone":null},{"type":"work","duration_type":"time","duration_value":300,"target_split":{"min":1100,"max":1200},"target_stroke_rate":{"min":24,"max":28},"target_hr_zone":4},{"type":"rest","duration_type":"time","duration_value":120,"target_split":null,"target_stroke_rate":null,"target_hr_zone":null},{"type":"work","duration_type":"time","duration_value":300,"target_split":{"min":1100,"max":1200},"target_stroke_rate":{"min":24,"max":28},"target_hr_zone":4},{"type":"rest","duration_type":"time","duration_value":120,"target_split":null,"target_stroke_rate":null,"target_hr_zone":null}]'::jsonb WHERE id = 'e1000000-0000-0000-0002-000000000001';

-- FTP Builder — Wk2 VO2max
UPDATE public.workouts SET segments = '[{"type":"work","duration_type":"time","duration_value":120,"target_split":{"min":1150,"max":1300},"target_stroke_rate":{"min":28,"max":32},"target_hr_zone":5},{"type":"rest","duration_type":"time","duration_value":120,"target_split":null,"target_stroke_rate":null,"target_hr_zone":null},{"type":"work","duration_type":"time","duration_value":120,"target_split":{"min":1150,"max":1300},"target_stroke_rate":{"min":28,"max":32},"target_hr_zone":5},{"type":"rest","duration_type":"time","duration_value":120,"target_split":null,"target_stroke_rate":null,"target_hr_zone":null},{"type":"work","duration_type":"time","duration_value":120,"target_split":{"min":1150,"max":1300},"target_stroke_rate":{"min":28,"max":32},"target_hr_zone":5},{"type":"rest","duration_type":"time","duration_value":120,"target_split":null,"target_stroke_rate":null,"target_hr_zone":null},{"type":"work","duration_type":"time","duration_value":120,"target_split":{"min":1150,"max":1300},"target_stroke_rate":{"min":28,"max":32},"target_hr_zone":5},{"type":"rest","duration_type":"time","duration_value":120,"target_split":null,"target_stroke_rate":null,"target_hr_zone":null},{"type":"work","duration_type":"time","duration_value":120,"target_split":{"min":1150,"max":1300},"target_stroke_rate":{"min":28,"max":32},"target_hr_zone":5},{"type":"rest","duration_type":"time","duration_value":120,"target_split":null,"target_stroke_rate":null,"target_hr_zone":null},{"type":"work","duration_type":"time","duration_value":120,"target_split":{"min":1150,"max":1300},"target_stroke_rate":{"min":28,"max":32},"target_hr_zone":5},{"type":"rest","duration_type":"time","duration_value":120,"target_split":null,"target_stroke_rate":null,"target_hr_zone":null}]'::jsonb WHERE id = 'e1000000-0000-0000-0002-000000000002';

-- FTP Builder — Wk2 Steady State
UPDATE public.workouts SET segments = '[{"type":"work","duration_type":"time","duration_value":2100,"target_split":{"min":1200,"max":1400},"target_stroke_rate":{"min":18,"max":22},"target_hr_zone":2}]'::jsonb WHERE id = 'e1000000-0000-0000-0002-000000000003';

-- FTP Builder — Wk3 Threshold
UPDATE public.workouts SET segments = '[{"type":"work","duration_type":"time","duration_value":300,"target_split":{"min":1080,"max":1180},"target_stroke_rate":{"min":24,"max":28},"target_hr_zone":4},{"type":"rest","duration_type":"time","duration_value":120,"target_split":null,"target_stroke_rate":null,"target_hr_zone":null},{"type":"work","duration_type":"time","duration_value":300,"target_split":{"min":1080,"max":1180},"target_stroke_rate":{"min":24,"max":28},"target_hr_zone":4},{"type":"rest","duration_type":"time","duration_value":120,"target_split":null,"target_stroke_rate":null,"target_hr_zone":null},{"type":"work","duration_type":"time","duration_value":300,"target_split":{"min":1080,"max":1180},"target_stroke_rate":{"min":24,"max":28},"target_hr_zone":4},{"type":"rest","duration_type":"time","duration_value":120,"target_split":null,"target_stroke_rate":null,"target_hr_zone":null},{"type":"work","duration_type":"time","duration_value":300,"target_split":{"min":1080,"max":1180},"target_stroke_rate":{"min":24,"max":28},"target_hr_zone":4},{"type":"rest","duration_type":"time","duration_value":120,"target_split":null,"target_stroke_rate":null,"target_hr_zone":null},{"type":"work","duration_type":"time","duration_value":300,"target_split":{"min":1080,"max":1180},"target_stroke_rate":{"min":24,"max":28},"target_hr_zone":4},{"type":"rest","duration_type":"time","duration_value":120,"target_split":null,"target_stroke_rate":null,"target_hr_zone":null}]'::jsonb WHERE id = 'e1000000-0000-0000-0003-000000000001';

-- FTP Builder — Wk3 VO2max
UPDATE public.workouts SET segments = '[{"type":"work","duration_type":"time","duration_value":90,"target_split":{"min":980,"max":1080},"target_stroke_rate":{"min":30,"max":34},"target_hr_zone":5},{"type":"rest","duration_type":"time","duration_value":90,"target_split":null,"target_stroke_rate":null,"target_hr_zone":null},{"type":"work","duration_type":"time","duration_value":90,"target_split":{"min":980,"max":1080},"target_stroke_rate":{"min":30,"max":34},"target_hr_zone":5},{"type":"rest","duration_type":"time","duration_value":90,"target_split":null,"target_stroke_rate":null,"target_hr_zone":null},{"type":"work","duration_type":"time","duration_value":90,"target_split":{"min":980,"max":1080},"target_stroke_rate":{"min":30,"max":34},"target_hr_zone":5},{"type":"rest","duration_type":"time","duration_value":90,"target_split":null,"target_stroke_rate":null,"target_hr_zone":null},{"type":"work","duration_type":"time","duration_value":90,"target_split":{"min":980,"max":1080},"target_stroke_rate":{"min":30,"max":34},"target_hr_zone":5},{"type":"rest","duration_type":"time","duration_value":90,"target_split":null,"target_stroke_rate":null,"target_hr_zone":null},{"type":"work","duration_type":"time","duration_value":90,"target_split":{"min":980,"max":1080},"target_stroke_rate":{"min":30,"max":34},"target_hr_zone":5},{"type":"rest","duration_type":"time","duration_value":90,"target_split":null,"target_stroke_rate":null,"target_hr_zone":null},{"type":"work","duration_type":"time","duration_value":90,"target_split":{"min":980,"max":1080},"target_stroke_rate":{"min":30,"max":34},"target_hr_zone":5},{"type":"rest","duration_type":"time","duration_value":90,"target_split":null,"target_stroke_rate":null,"target_hr_zone":null},{"type":"work","duration_type":"time","duration_value":90,"target_split":{"min":980,"max":1080},"target_stroke_rate":{"min":30,"max":34},"target_hr_zone":5},{"type":"rest","duration_type":"time","duration_value":90,"target_split":null,"target_stroke_rate":null,"target_hr_zone":null},{"type":"work","duration_type":"time","duration_value":90,"target_split":{"min":980,"max":1080},"target_stroke_rate":{"min":30,"max":34},"target_hr_zone":5},{"type":"rest","duration_type":"time","duration_value":90,"target_split":null,"target_stroke_rate":null,"target_hr_zone":null}]'::jsonb WHERE id = 'e1000000-0000-0000-0003-000000000002';

-- FTP Builder — Wk3 Steady State
UPDATE public.workouts SET segments = '[{"type":"work","duration_type":"time","duration_value":2400,"target_split":{"min":1200,"max":1400},"target_stroke_rate":{"min":18,"max":22},"target_hr_zone":2}]'::jsonb WHERE id = 'e1000000-0000-0000-0003-000000000003';

-- FTP Builder — Wk4 Threshold
UPDATE public.workouts SET segments = '[{"type":"work","duration_type":"time","duration_value":480,"target_split":{"min":1080,"max":1170},"target_stroke_rate":{"min":24,"max":28},"target_hr_zone":4},{"type":"rest","duration_type":"time","duration_value":180,"target_split":null,"target_stroke_rate":null,"target_hr_zone":null},{"type":"work","duration_type":"time","duration_value":480,"target_split":{"min":1080,"max":1170},"target_stroke_rate":{"min":24,"max":28},"target_hr_zone":4},{"type":"rest","duration_type":"time","duration_value":180,"target_split":null,"target_stroke_rate":null,"target_hr_zone":null},{"type":"work","duration_type":"time","duration_value":480,"target_split":{"min":1080,"max":1170},"target_stroke_rate":{"min":24,"max":28},"target_hr_zone":4},{"type":"rest","duration_type":"time","duration_value":180,"target_split":null,"target_stroke_rate":null,"target_hr_zone":null}]'::jsonb WHERE id = 'e1000000-0000-0000-0004-000000000001';

-- FTP Builder — Wk4 VO2max
UPDATE public.workouts SET segments = '[{"type":"work","duration_type":"time","duration_value":180,"target_split":{"min":1000,"max":1080},"target_stroke_rate":{"min":28,"max":32},"target_hr_zone":5},{"type":"rest","duration_type":"time","duration_value":180,"target_split":null,"target_stroke_rate":null,"target_hr_zone":null},{"type":"work","duration_type":"time","duration_value":180,"target_split":{"min":1000,"max":1080},"target_stroke_rate":{"min":28,"max":32},"target_hr_zone":5},{"type":"rest","duration_type":"time","duration_value":180,"target_split":null,"target_stroke_rate":null,"target_hr_zone":null},{"type":"work","duration_type":"time","duration_value":180,"target_split":{"min":1000,"max":1080},"target_stroke_rate":{"min":28,"max":32},"target_hr_zone":5},{"type":"rest","duration_type":"time","duration_value":180,"target_split":null,"target_stroke_rate":null,"target_hr_zone":null},{"type":"work","duration_type":"time","duration_value":180,"target_split":{"min":1000,"max":1080},"target_stroke_rate":{"min":28,"max":32},"target_hr_zone":5},{"type":"rest","duration_type":"time","duration_value":180,"target_split":null,"target_stroke_rate":null,"target_hr_zone":null},{"type":"work","duration_type":"time","duration_value":180,"target_split":{"min":1000,"max":1080},"target_stroke_rate":{"min":28,"max":32},"target_hr_zone":5},{"type":"rest","duration_type":"time","duration_value":180,"target_split":null,"target_stroke_rate":null,"target_hr_zone":null}]'::jsonb WHERE id = 'e1000000-0000-0000-0004-000000000002';

-- FTP Builder — Wk4 Steady State
UPDATE public.workouts SET segments = '[{"type":"work","duration_type":"time","duration_value":2400,"target_split":{"min":1200,"max":1350},"target_stroke_rate":{"min":18,"max":22},"target_hr_zone":2}]'::jsonb WHERE id = 'e1000000-0000-0000-0004-000000000003';

-- FTP Builder — Wk5 Threshold
UPDATE public.workouts SET segments = '[{"type":"work","duration_type":"time","duration_value":720,"target_split":{"min":1070,"max":1160},"target_stroke_rate":{"min":24,"max":28},"target_hr_zone":4},{"type":"rest","duration_type":"time","duration_value":240,"target_split":null,"target_stroke_rate":null,"target_hr_zone":null},{"type":"work","duration_type":"time","duration_value":720,"target_split":{"min":1070,"max":1160},"target_stroke_rate":{"min":24,"max":28},"target_hr_zone":4},{"type":"rest","duration_type":"time","duration_value":240,"target_split":null,"target_stroke_rate":null,"target_hr_zone":null}]'::jsonb WHERE id = 'e1000000-0000-0000-0005-000000000001';

-- FTP Builder — Wk5 VO2max
UPDATE public.workouts SET segments = '[{"type":"work","duration_type":"time","duration_value":240,"target_split":{"min":1000,"max":1070},"target_stroke_rate":{"min":28,"max":32},"target_hr_zone":5},{"type":"rest","duration_type":"time","duration_value":240,"target_split":null,"target_stroke_rate":null,"target_hr_zone":null},{"type":"work","duration_type":"time","duration_value":240,"target_split":{"min":1000,"max":1070},"target_stroke_rate":{"min":28,"max":32},"target_hr_zone":5},{"type":"rest","duration_type":"time","duration_value":240,"target_split":null,"target_stroke_rate":null,"target_hr_zone":null},{"type":"work","duration_type":"time","duration_value":240,"target_split":{"min":1000,"max":1070},"target_stroke_rate":{"min":28,"max":32},"target_hr_zone":5},{"type":"rest","duration_type":"time","duration_value":240,"target_split":null,"target_stroke_rate":null,"target_hr_zone":null},{"type":"work","duration_type":"time","duration_value":240,"target_split":{"min":1000,"max":1070},"target_stroke_rate":{"min":28,"max":32},"target_hr_zone":5},{"type":"rest","duration_type":"time","duration_value":240,"target_split":null,"target_stroke_rate":null,"target_hr_zone":null}]'::jsonb WHERE id = 'e1000000-0000-0000-0005-000000000002';

-- FTP Builder — Wk5 Steady State
UPDATE public.workouts SET segments = '[{"type":"work","duration_type":"time","duration_value":2100,"target_split":{"min":1200,"max":1350},"target_stroke_rate":{"min":18,"max":22},"target_hr_zone":2}]'::jsonb WHERE id = 'e1000000-0000-0000-0005-000000000003';

-- FTP Builder — Wk6 Recovery
UPDATE public.workouts SET segments = '[{"type":"work","duration_type":"time","duration_value":1200,"target_split":{"min":1350,"max":1600},"target_stroke_rate":{"min":16,"max":20},"target_hr_zone":1}]'::jsonb WHERE id = 'e1000000-0000-0000-0006-000000000001';

-- FTP Builder — Wk6 Steady State
UPDATE public.workouts SET segments = '[{"type":"work","duration_type":"time","duration_value":1500,"target_split":{"min":1200,"max":1400},"target_stroke_rate":{"min":18,"max":22},"target_hr_zone":2}]'::jsonb WHERE id = 'e1000000-0000-0000-0006-000000000002';

-- 2K Race Prep — Wk1 Steady State
UPDATE public.workouts SET segments = '[{"type":"work","duration_type":"time","duration_value":1800,"target_split":{"min":1300,"max":1500},"target_stroke_rate":{"min":20,"max":24},"target_hr_zone":3}]'::jsonb WHERE id = 'f1000000-0000-0000-0001-000000000001';

-- 2K Race Prep — Wk1 Race Pace 4x500m
UPDATE public.workouts SET segments = '[{"type":"work","duration_type":"distance","duration_value":500,"target_split":{"min":950,"max":1050},"target_stroke_rate":{"min":30,"max":34},"target_hr_zone":5},{"type":"rest","duration_type":"time","duration_value":180,"target_split":null,"target_stroke_rate":null,"target_hr_zone":null},{"type":"work","duration_type":"distance","duration_value":500,"target_split":{"min":950,"max":1050},"target_stroke_rate":{"min":30,"max":34},"target_hr_zone":5},{"type":"rest","duration_type":"time","duration_value":180,"target_split":null,"target_stroke_rate":null,"target_hr_zone":null},{"type":"work","duration_type":"distance","duration_value":500,"target_split":{"min":950,"max":1050},"target_stroke_rate":{"min":30,"max":34},"target_hr_zone":5},{"type":"rest","duration_type":"time","duration_value":180,"target_split":null,"target_stroke_rate":null,"target_hr_zone":null},{"type":"work","duration_type":"distance","duration_value":500,"target_split":{"min":950,"max":1050},"target_stroke_rate":{"min":30,"max":34},"target_hr_zone":5},{"type":"rest","duration_type":"time","duration_value":180,"target_split":null,"target_stroke_rate":null,"target_hr_zone":null}]'::jsonb WHERE id = 'f1000000-0000-0000-0001-000000000002';

-- 2K Race Prep — Wk1 Easy Distance
UPDATE public.workouts SET segments = '[{"type":"work","duration_type":"distance","duration_value":5000,"target_split":{"min":1250,"max":1450},"target_stroke_rate":{"min":18,"max":22},"target_hr_zone":2}]'::jsonb WHERE id = 'f1000000-0000-0000-0001-000000000003';

-- 2K Race Prep — Wk2 Tempo 3K
UPDATE public.workouts SET segments = '[{"type":"work","duration_type":"distance","duration_value":3000,"target_split":{"min":1020,"max":1120},"target_stroke_rate":{"min":26,"max":30},"target_hr_zone":4}]'::jsonb WHERE id = 'f1000000-0000-0000-0002-000000000001';

-- 2K Race Prep — Wk2 Race Pace 6x500m
UPDATE public.workouts SET segments = '[{"type":"work","duration_type":"distance","duration_value":500,"target_split":{"min":950,"max":1050},"target_stroke_rate":{"min":30,"max":34},"target_hr_zone":5},{"type":"rest","duration_type":"time","duration_value":150,"target_split":null,"target_stroke_rate":null,"target_hr_zone":null},{"type":"work","duration_type":"distance","duration_value":500,"target_split":{"min":950,"max":1050},"target_stroke_rate":{"min":30,"max":34},"target_hr_zone":5},{"type":"rest","duration_type":"time","duration_value":150,"target_split":null,"target_stroke_rate":null,"target_hr_zone":null},{"type":"work","duration_type":"distance","duration_value":500,"target_split":{"min":950,"max":1050},"target_stroke_rate":{"min":30,"max":34},"target_hr_zone":5},{"type":"rest","duration_type":"time","duration_value":150,"target_split":null,"target_stroke_rate":null,"target_hr_zone":null},{"type":"work","duration_type":"distance","duration_value":500,"target_split":{"min":950,"max":1050},"target_stroke_rate":{"min":30,"max":34},"target_hr_zone":5},{"type":"rest","duration_type":"time","duration_value":150,"target_split":null,"target_stroke_rate":null,"target_hr_zone":null},{"type":"work","duration_type":"distance","duration_value":500,"target_split":{"min":950,"max":1050},"target_stroke_rate":{"min":30,"max":34},"target_hr_zone":5},{"type":"rest","duration_type":"time","duration_value":150,"target_split":null,"target_stroke_rate":null,"target_hr_zone":null},{"type":"work","duration_type":"distance","duration_value":500,"target_split":{"min":950,"max":1050},"target_stroke_rate":{"min":30,"max":34},"target_hr_zone":5},{"type":"rest","duration_type":"time","duration_value":150,"target_split":null,"target_stroke_rate":null,"target_hr_zone":null}]'::jsonb WHERE id = 'f1000000-0000-0000-0002-000000000002';

-- 2K Race Prep — Wk2 Easy Distance
UPDATE public.workouts SET segments = '[{"type":"work","duration_type":"distance","duration_value":6000,"target_split":{"min":1250,"max":1450},"target_stroke_rate":{"min":18,"max":22},"target_hr_zone":2}]'::jsonb WHERE id = 'f1000000-0000-0000-0002-000000000003';

-- 2K Race Prep — Wk3 Threshold 2x1500m
UPDATE public.workouts SET segments = '[{"type":"work","duration_type":"distance","duration_value":1500,"target_split":{"min":1000,"max":1080},"target_stroke_rate":{"min":28,"max":32},"target_hr_zone":4},{"type":"rest","duration_type":"time","duration_value":300,"target_split":null,"target_stroke_rate":null,"target_hr_zone":null},{"type":"work","duration_type":"distance","duration_value":1500,"target_split":{"min":1000,"max":1080},"target_stroke_rate":{"min":28,"max":32},"target_hr_zone":4},{"type":"rest","duration_type":"time","duration_value":300,"target_split":null,"target_stroke_rate":null,"target_hr_zone":null}]'::jsonb WHERE id = 'f1000000-0000-0000-0003-000000000001';

-- 2K Race Prep — Wk3 Race Pace 8x500m
UPDATE public.workouts SET segments = '[{"type":"work","duration_type":"distance","duration_value":500,"target_split":{"min":950,"max":1050},"target_stroke_rate":{"min":30,"max":34},"target_hr_zone":5},{"type":"rest","duration_type":"time","duration_value":120,"target_split":null,"target_stroke_rate":null,"target_hr_zone":null},{"type":"work","duration_type":"distance","duration_value":500,"target_split":{"min":950,"max":1050},"target_stroke_rate":{"min":30,"max":34},"target_hr_zone":5},{"type":"rest","duration_type":"time","duration_value":120,"target_split":null,"target_stroke_rate":null,"target_hr_zone":null},{"type":"work","duration_type":"distance","duration_value":500,"target_split":{"min":950,"max":1050},"target_stroke_rate":{"min":30,"max":34},"target_hr_zone":5},{"type":"rest","duration_type":"time","duration_value":120,"target_split":null,"target_stroke_rate":null,"target_hr_zone":null},{"type":"work","duration_type":"distance","duration_value":500,"target_split":{"min":950,"max":1050},"target_stroke_rate":{"min":30,"max":34},"target_hr_zone":5},{"type":"rest","duration_type":"time","duration_value":120,"target_split":null,"target_stroke_rate":null,"target_hr_zone":null},{"type":"work","duration_type":"distance","duration_value":500,"target_split":{"min":950,"max":1050},"target_stroke_rate":{"min":30,"max":34},"target_hr_zone":5},{"type":"rest","duration_type":"time","duration_value":120,"target_split":null,"target_stroke_rate":null,"target_hr_zone":null},{"type":"work","duration_type":"distance","duration_value":500,"target_split":{"min":950,"max":1050},"target_stroke_rate":{"min":30,"max":34},"target_hr_zone":5},{"type":"rest","duration_type":"time","duration_value":120,"target_split":null,"target_stroke_rate":null,"target_hr_zone":null},{"type":"work","duration_type":"distance","duration_value":500,"target_split":{"min":950,"max":1050},"target_stroke_rate":{"min":30,"max":34},"target_hr_zone":5},{"type":"rest","duration_type":"time","duration_value":120,"target_split":null,"target_stroke_rate":null,"target_hr_zone":null},{"type":"work","duration_type":"distance","duration_value":500,"target_split":{"min":950,"max":1050},"target_stroke_rate":{"min":30,"max":34},"target_hr_zone":5},{"type":"rest","duration_type":"time","duration_value":120,"target_split":null,"target_stroke_rate":null,"target_hr_zone":null}]'::jsonb WHERE id = 'f1000000-0000-0000-0003-000000000002';

-- 2K Race Prep — Wk3 Easy Recovery
UPDATE public.workouts SET segments = '[{"type":"work","duration_type":"time","duration_value":1200,"target_split":{"min":1350,"max":1600},"target_stroke_rate":{"min":16,"max":20},"target_hr_zone":1}]'::jsonb WHERE id = 'f1000000-0000-0000-0003-000000000003';

-- 2K Race Prep — Wk4 Shakeout
UPDATE public.workouts SET segments = '[{"type":"warmup","duration_type":"time","duration_value":300,"target_split":{"min":1350,"max":1600},"target_stroke_rate":{"min":16,"max":20}},{"type":"work","duration_type":"time","duration_value":30,"target_split":{"min":1150,"max":1300},"target_stroke_rate":{"min":28,"max":32}},{"type":"rest","duration_type":"time","duration_value":90,"target_split":null,"target_stroke_rate":null},{"type":"work","duration_type":"time","duration_value":30,"target_split":{"min":1150,"max":1300},"target_stroke_rate":{"min":28,"max":32}},{"type":"rest","duration_type":"time","duration_value":90,"target_split":null,"target_stroke_rate":null},{"type":"work","duration_type":"time","duration_value":30,"target_split":{"min":1150,"max":1300},"target_stroke_rate":{"min":28,"max":32}},{"type":"rest","duration_type":"time","duration_value":90,"target_split":null,"target_stroke_rate":null},{"type":"cooldown","duration_type":"time","duration_value":300,"target_split":{"min":1350,"max":1600},"target_stroke_rate":{"min":16,"max":20}}]'::jsonb WHERE id = 'f1000000-0000-0000-0004-000000000001';

-- 2K Race Prep — Wk4 Openers
UPDATE public.workouts SET segments = '[{"type":"work","duration_type":"distance","duration_value":250,"target_split":{"min":940,"max":1020},"target_stroke_rate":{"min":32,"max":36},"target_hr_zone":5},{"type":"rest","duration_type":"time","duration_value":240,"target_split":null,"target_stroke_rate":null,"target_hr_zone":null},{"type":"work","duration_type":"distance","duration_value":250,"target_split":{"min":940,"max":1020},"target_stroke_rate":{"min":32,"max":36},"target_hr_zone":5},{"type":"rest","duration_type":"time","duration_value":240,"target_split":null,"target_stroke_rate":null,"target_hr_zone":null},{"type":"work","duration_type":"distance","duration_value":250,"target_split":{"min":940,"max":1020},"target_stroke_rate":{"min":32,"max":36},"target_hr_zone":5},{"type":"rest","duration_type":"time","duration_value":240,"target_split":null,"target_stroke_rate":null,"target_hr_zone":null},{"type":"work","duration_type":"distance","duration_value":250,"target_split":{"min":940,"max":1020},"target_stroke_rate":{"min":32,"max":36},"target_hr_zone":5},{"type":"rest","duration_type":"time","duration_value":240,"target_split":null,"target_stroke_rate":null,"target_hr_zone":null}]'::jsonb WHERE id = 'f1000000-0000-0000-0004-000000000002';
